/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiSetoranListQueryResponse, GetApiSetoranListQueryParams } from '../../types/SetoranController/GetApiSetoranList.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getApiSetoranListSuspenseQueryKey = (params?: GetApiSetoranListQueryParams) => [{ url: '/api/Setoran/list' }, ...(params ? [params] : [])] as const

export type GetApiSetoranListSuspenseQueryKey = ReturnType<typeof getApiSetoranListSuspenseQueryKey>

/**
 * {@link /api/Setoran/list}
 */
export async function getApiSetoranListSuspense(params?: GetApiSetoranListQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiSetoranListQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/Setoran/list`,
    params,
    ...requestConfig,
  })
  return res
}

export function getApiSetoranListSuspenseQueryOptions(params?: GetApiSetoranListQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiSetoranListSuspenseQueryKey(params)
  return queryOptions<
    ResponseConfig<GetApiSetoranListQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiSetoranListQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiSetoranListSuspense(params, config)
    },
  })
}

/**
 * {@link /api/Setoran/list}
 */
export function useGetApiSetoranListSuspense<
  TData = ResponseConfig<GetApiSetoranListQueryResponse>,
  TQueryKey extends QueryKey = GetApiSetoranListSuspenseQueryKey,
>(
  params?: GetApiSetoranListQueryParams,
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetApiSetoranListQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiSetoranListSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...(getApiSetoranListSuspenseQueryOptions(params, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}