/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiSetoranListQueryResponse, GetApiSetoranListQueryParams } from '../../types/SetoranController/GetApiSetoranList.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getApiSetoranListQueryKey = (params?: GetApiSetoranListQueryParams) => [{ url: '/api/Setoran/list' }, ...(params ? [params] : [])] as const

export type GetApiSetoranListQueryKey = ReturnType<typeof getApiSetoranListQueryKey>

/**
 * {@link /api/Setoran/list}
 */
export async function getApiSetoranList(params?: GetApiSetoranListQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiSetoranListQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/Setoran/list`,
    params,
    ...requestConfig,
  })
  return res
}

export function getApiSetoranListQueryOptions(params?: GetApiSetoranListQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiSetoranListQueryKey(params)
  return queryOptions<
    ResponseConfig<GetApiSetoranListQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiSetoranListQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiSetoranList(params, config)
    },
  })
}

/**
 * {@link /api/Setoran/list}
 */
export function useGetApiSetoranList<
  TData = ResponseConfig<GetApiSetoranListQueryResponse>,
  TQueryData = ResponseConfig<GetApiSetoranListQueryResponse>,
  TQueryKey extends QueryKey = GetApiSetoranListQueryKey,
>(
  params?: GetApiSetoranListQueryParams,
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<GetApiSetoranListQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiSetoranListQueryKey(params)

  const query = useQuery(
    {
      ...(getApiSetoranListQueryOptions(params, config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}