/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '@/config/axiosClient.ts'
import type {
  PostApiSetoranSetorMutationRequest,
  PostApiSetoranSetorMutationResponse,
  PostApiSetoranSetorQueryParams,
} from '../../types/SetoranController/PostApiSetoranSetor.ts'
import { useMutation } from '@tanstack/react-query'

export const postApiSetoranSetorMutationKey = () => [{ url: '/api/Setoran/setor' }] as const

export type PostApiSetoranSetorMutationKey = ReturnType<typeof postApiSetoranSetorMutationKey>

/**
 * {@link /api/Setoran/setor}
 */
export async function postApiSetoranSetor(
  data?: PostApiSetoranSetorMutationRequest,
  params?: PostApiSetoranSetorQueryParams,
  config: Partial<RequestConfig<PostApiSetoranSetorMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<PostApiSetoranSetorMutationResponse, ResponseErrorConfig<Error>, PostApiSetoranSetorMutationRequest>({
    method: 'POST',
    url: `/api/Setoran/setor`,
    params,
    data,
    ...requestConfig,
    headers: { 'Content-Type': 'application/*+json', ...requestConfig.headers },
  })
  return res
}

/**
 * {@link /api/Setoran/setor}
 */
export function usePostApiSetoranSetor<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ResponseConfig<PostApiSetoranSetorMutationResponse>,
      ResponseErrorConfig<Error>,
      { data?: PostApiSetoranSetorMutationRequest; params?: PostApiSetoranSetorQueryParams },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PostApiSetoranSetorMutationRequest>> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? postApiSetoranSetorMutationKey()

  return useMutation<
    ResponseConfig<PostApiSetoranSetorMutationResponse>,
    ResponseErrorConfig<Error>,
    { data?: PostApiSetoranSetorMutationRequest; params?: PostApiSetoranSetorQueryParams },
    TContext
  >(
    {
      mutationFn: async ({ data, params }) => {
        return postApiSetoranSetor(data, params, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}