/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetApiOpsibandingQueryParams = {
  /**
   * @type integer | undefined, int32
   */
  rencanaBandingId?: number
}

/**
 * @description OK
 */
export type GetApiOpsibanding200 = any

export type GetApiOpsibandingQueryResponse = GetApiOpsibanding200

export type GetApiOpsibandingQuery = {
  Response: GetApiOpsibanding200
  QueryParams: GetApiOpsibandingQueryParams
  Errors: any
}