/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { OpsiBandingCreateDto } from '../OpsiBandingCreateDto.ts'

/**
 * @description OK
 */
export type PostApiOpsibanding200 = any

export type PostApiOpsibandingMutationRequest = OpsiBandingCreateDto

export type PostApiOpsibandingMutationResponse = PostApiOpsibanding200

export type PostApiOpsibandingMutation = {
  Response: PostApiOpsibanding200
  Request: PostApiOpsibandingMutationRequest
  Errors: any
}