/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { SaranKeuanganDto } from '../SaranKeuanganDto.ts'

/**
 * @description OK
 */
export type GetApiSmartassistantSaran200 = SaranKeuanganDto

export type GetApiSmartassistantSaranQueryResponse = GetApiSmartassistantSaran200

export type GetApiSmartassistantSaranQuery = {
  Response: GetApiSmartassistantSaran200
  Errors: any
}