/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { GetApiAuthProtectedEndpointQueryResponse } from '../../types/AuthController/GetApiAuthProtectedEndpoint.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getApiAuthProtectedEndpointSuspenseQueryKey = () => [{ url: '/api/auth/protected-endpoint' }] as const

export type GetApiAuthProtectedEndpointSuspenseQueryKey = ReturnType<typeof getApiAuthProtectedEndpointSuspenseQueryKey>

/**
 * {@link /api/auth/protected-endpoint}
 */
export async function getApiAuthProtectedEndpointSuspense(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiAuthProtectedEndpointQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/auth/protected-endpoint`,
    ...requestConfig,
  })
  return res
}

export function getApiAuthProtectedEndpointSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiAuthProtectedEndpointSuspenseQueryKey()
  return queryOptions<
    ResponseConfig<GetApiAuthProtectedEndpointQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiAuthProtectedEndpointQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiAuthProtectedEndpointSuspense(config)
    },
  })
}

/**
 * {@link /api/auth/protected-endpoint}
 */
export function useGetApiAuthProtectedEndpointSuspense<
  TData = ResponseConfig<GetApiAuthProtectedEndpointQueryResponse>,
  TQueryKey extends QueryKey = GetApiAuthProtectedEndpointSuspenseQueryKey,
>(
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetApiAuthProtectedEndpointQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiAuthProtectedEndpointSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...(getApiAuthProtectedEndpointSuspenseQueryOptions(config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}