/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { GetApiAuthCheckAuthQueryResponse } from '../../types/AuthController/GetApiAuthCheckAuth.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getApiAuthCheckAuthQueryKey = () => [{ url: '/api/auth/check-auth' }] as const

export type GetApiAuthCheckAuthQueryKey = ReturnType<typeof getApiAuthCheckAuthQueryKey>

/**
 * {@link /api/auth/check-auth}
 */
export async function getApiAuthCheckAuth(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiAuthCheckAuthQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/auth/check-auth`,
    ...requestConfig,
  })
  return res
}

export function getApiAuthCheckAuthQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiAuthCheckAuthQueryKey()
  return queryOptions<
    ResponseConfig<GetApiAuthCheckAuthQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiAuthCheckAuthQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiAuthCheckAuth(config)
    },
  })
}

/**
 * {@link /api/auth/check-auth}
 */
export function useGetApiAuthCheckAuth<
  TData = ResponseConfig<GetApiAuthCheckAuthQueryResponse>,
  TQueryData = ResponseConfig<GetApiAuthCheckAuthQueryResponse>,
  TQueryKey extends QueryKey = GetApiAuthCheckAuthQueryKey,
>(
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<GetApiAuthCheckAuthQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiAuthCheckAuthQueryKey()

  const query = useQuery(
    {
      ...(getApiAuthCheckAuthQueryOptions(config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}