/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import type { GetApiAuthProtectedEndpointQueryResponse } from '../../types/AuthController/GetApiAuthProtectedEndpoint.ts'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getApiAuthProtectedEndpointInfiniteQueryKey = () => [{ url: '/api/auth/protected-endpoint' }] as const

export type GetApiAuthProtectedEndpointInfiniteQueryKey = ReturnType<typeof getApiAuthProtectedEndpointInfiniteQueryKey>

/**
 * {@link /api/auth/protected-endpoint}
 */
export async function getApiAuthProtectedEndpointInfinite(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiAuthProtectedEndpointQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/auth/protected-endpoint`,
    ...requestConfig,
  })
  return res
}

export function getApiAuthProtectedEndpointInfiniteQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiAuthProtectedEndpointInfiniteQueryKey()
  return infiniteQueryOptions<
    ResponseConfig<GetApiAuthProtectedEndpointQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiAuthProtectedEndpointQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiAuthProtectedEndpointInfinite(config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * {@link /api/auth/protected-endpoint}
 */
export function useGetApiAuthProtectedEndpointInfinite<
  TData = InfiniteData<ResponseConfig<GetApiAuthProtectedEndpointQueryResponse>>,
  TQueryData = ResponseConfig<GetApiAuthProtectedEndpointQueryResponse>,
  TQueryKey extends QueryKey = GetApiAuthProtectedEndpointInfiniteQueryKey,
>(
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetApiAuthProtectedEndpointQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiAuthProtectedEndpointInfiniteQueryKey()

  const query = useInfiniteQuery(
    {
      ...(getApiAuthProtectedEndpointInfiniteQueryOptions(config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}