/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import type { GetApiAuthCheckAuthQueryResponse } from '../../types/AuthController/GetApiAuthCheckAuth.ts'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getApiAuthCheckAuthInfiniteQueryKey = () => [{ url: '/api/auth/check-auth' }] as const

export type GetApiAuthCheckAuthInfiniteQueryKey = ReturnType<typeof getApiAuthCheckAuthInfiniteQueryKey>

/**
 * {@link /api/auth/check-auth}
 */
export async function getApiAuthCheckAuthInfinite(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiAuthCheckAuthQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/auth/check-auth`,
    ...requestConfig,
  })
  return res
}

export function getApiAuthCheckAuthInfiniteQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiAuthCheckAuthInfiniteQueryKey()
  return infiniteQueryOptions<
    ResponseConfig<GetApiAuthCheckAuthQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiAuthCheckAuthQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiAuthCheckAuthInfinite(config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * {@link /api/auth/check-auth}
 */
export function useGetApiAuthCheckAuthInfinite<
  TData = InfiniteData<ResponseConfig<GetApiAuthCheckAuthQueryResponse>>,
  TQueryData = ResponseConfig<GetApiAuthCheckAuthQueryResponse>,
  TQueryKey extends QueryKey = GetApiAuthCheckAuthInfiniteQueryKey,
>(
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetApiAuthCheckAuthQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiAuthCheckAuthInfiniteQueryKey()

  const query = useInfiniteQuery(
    {
      ...(getApiAuthCheckAuthInfiniteQueryOptions(config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}