/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import type { GetApiAuthMeQueryResponse } from '../../types/AuthController/GetApiAuthMe.ts'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getApiAuthMeInfiniteQueryKey = () => [{ url: '/api/auth/me' }] as const

export type GetApiAuthMeInfiniteQueryKey = ReturnType<typeof getApiAuthMeInfiniteQueryKey>

/**
 * {@link /api/auth/me}
 */
export async function getApiAuthMeInfinite(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiAuthMeQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/api/auth/me`, ...requestConfig })
  return res
}

export function getApiAuthMeInfiniteQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiAuthMeInfiniteQueryKey()
  return infiniteQueryOptions<
    ResponseConfig<GetApiAuthMeQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiAuthMeQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiAuthMeInfinite(config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * {@link /api/auth/me}
 */
export function useGetApiAuthMeInfinite<
  TData = InfiniteData<ResponseConfig<GetApiAuthMeQueryResponse>>,
  TQueryData = ResponseConfig<GetApiAuthMeQueryResponse>,
  TQueryKey extends QueryKey = GetApiAuthMeInfiniteQueryKey,
>(
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetApiAuthMeQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiAuthMeInfiniteQueryKey()

  const query = useInfiniteQuery(
    {
      ...(getApiAuthMeInfiniteQueryOptions(config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}