/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { GetApiAuthProtectedEndpointQueryResponse } from '../../types/AuthController/GetApiAuthProtectedEndpoint.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getApiAuthProtectedEndpointQueryKey = () => [{ url: '/api/auth/protected-endpoint' }] as const

export type GetApiAuthProtectedEndpointQueryKey = ReturnType<typeof getApiAuthProtectedEndpointQueryKey>

/**
 * {@link /api/auth/protected-endpoint}
 */
export async function getApiAuthProtectedEndpoint(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiAuthProtectedEndpointQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/auth/protected-endpoint`,
    ...requestConfig,
  })
  return res
}

export function getApiAuthProtectedEndpointQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiAuthProtectedEndpointQueryKey()
  return queryOptions<
    ResponseConfig<GetApiAuthProtectedEndpointQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiAuthProtectedEndpointQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiAuthProtectedEndpoint(config)
    },
  })
}

/**
 * {@link /api/auth/protected-endpoint}
 */
export function useGetApiAuthProtectedEndpoint<
  TData = ResponseConfig<GetApiAuthProtectedEndpointQueryResponse>,
  TQueryData = ResponseConfig<GetApiAuthProtectedEndpointQueryResponse>,
  TQueryKey extends QueryKey = GetApiAuthProtectedEndpointQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<ResponseConfig<GetApiAuthProtectedEndpointQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiAuthProtectedEndpointQueryKey()

  const query = useQuery(
    {
      ...(getApiAuthProtectedEndpointQueryOptions(config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}