/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '@/config/axiosClient.ts'
import type { PostApiAuthAuth0LoginMutationRequest, PostApiAuthAuth0LoginMutationResponse } from '../../types/AuthController/PostApiAuthAuth0Login.ts'
import { useMutation } from '@tanstack/react-query'

export const postApiAuthAuth0LoginMutationKey = () => [{ url: '/api/auth/auth0-login' }] as const

export type PostApiAuthAuth0LoginMutationKey = ReturnType<typeof postApiAuthAuth0LoginMutationKey>

/**
 * {@link /api/auth/auth0-login}
 */
export async function postApiAuthAuth0Login(
  data?: PostApiAuthAuth0LoginMutationRequest,
  config: Partial<RequestConfig<PostApiAuthAuth0LoginMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<PostApiAuthAuth0LoginMutationResponse, ResponseErrorConfig<Error>, PostApiAuthAuth0LoginMutationRequest>({
    method: 'POST',
    url: `/api/auth/auth0-login`,
    data,
    ...requestConfig,
    headers: { 'Content-Type': 'application/*+json', ...requestConfig.headers },
  })
  return res
}

/**
 * {@link /api/auth/auth0-login}
 */
export function usePostApiAuthAuth0Login<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ResponseConfig<PostApiAuthAuth0LoginMutationResponse>,
      ResponseErrorConfig<Error>,
      { data?: PostApiAuthAuth0LoginMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PostApiAuthAuth0LoginMutationRequest>> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? postApiAuthAuth0LoginMutationKey()

  return useMutation<
    ResponseConfig<PostApiAuthAuth0LoginMutationResponse>,
    ResponseErrorConfig<Error>,
    { data?: PostApiAuthAuth0LoginMutationRequest },
    TContext
  >(
    {
      mutationFn: async ({ data }) => {
        return postApiAuthAuth0Login(data, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}