/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '@/config/axiosClient.ts'
import type { PostApiAuthGoogleLoginMutationRequest, PostApiAuthGoogleLoginMutationResponse } from '../../types/AuthController/PostApiAuthGoogleLogin.ts'
import { useMutation } from '@tanstack/react-query'

export const postApiAuthGoogleLoginMutationKey = () => [{ url: '/api/auth/google-login' }] as const

export type PostApiAuthGoogleLoginMutationKey = ReturnType<typeof postApiAuthGoogleLoginMutationKey>

/**
 * {@link /api/auth/google-login}
 */
export async function postApiAuthGoogleLogin(
  data?: PostApiAuthGoogleLoginMutationRequest,
  config: Partial<RequestConfig<PostApiAuthGoogleLoginMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<PostApiAuthGoogleLoginMutationResponse, ResponseErrorConfig<Error>, PostApiAuthGoogleLoginMutationRequest>({
    method: 'POST',
    url: `/api/auth/google-login`,
    data,
    ...requestConfig,
    headers: { 'Content-Type': 'application/*+json', ...requestConfig.headers },
  })
  return res
}

/**
 * {@link /api/auth/google-login}
 */
export function usePostApiAuthGoogleLogin<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ResponseConfig<PostApiAuthGoogleLoginMutationResponse>,
      ResponseErrorConfig<Error>,
      { data?: PostApiAuthGoogleLoginMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PostApiAuthGoogleLoginMutationRequest>> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? postApiAuthGoogleLoginMutationKey()

  return useMutation<
    ResponseConfig<PostApiAuthGoogleLoginMutationResponse>,
    ResponseErrorConfig<Error>,
    { data?: PostApiAuthGoogleLoginMutationRequest },
    TContext
  >(
    {
      mutationFn: async ({ data }) => {
        return postApiAuthGoogleLogin(data, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}