/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '@/config/axiosClient.ts'
import type { PostApiAuthLoginMutationRequest, PostApiAuthLoginMutationResponse } from '../../types/AuthController/PostApiAuthLogin.ts'
import { useMutation } from '@tanstack/react-query'

export const postApiAuthLoginMutationKey = () => [{ url: '/api/auth/login' }] as const

export type PostApiAuthLoginMutationKey = ReturnType<typeof postApiAuthLoginMutationKey>

/**
 * {@link /api/auth/login}
 */
export async function postApiAuthLogin(
  data?: PostApiAuthLoginMutationRequest,
  config: Partial<RequestConfig<PostApiAuthLoginMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<PostApiAuthLoginMutationResponse, ResponseErrorConfig<Error>, PostApiAuthLoginMutationRequest>({
    method: 'POST',
    url: `/api/auth/login`,
    data,
    ...requestConfig,
    headers: { 'Content-Type': 'application/*+json', ...requestConfig.headers },
  })
  return res
}

/**
 * {@link /api/auth/login}
 */
export function usePostApiAuthLogin<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ResponseConfig<PostApiAuthLoginMutationResponse>,
      ResponseErrorConfig<Error>,
      { data?: PostApiAuthLoginMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PostApiAuthLoginMutationRequest>> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? postApiAuthLoginMutationKey()

  return useMutation<ResponseConfig<PostApiAuthLoginMutationResponse>, ResponseErrorConfig<Error>, { data?: PostApiAuthLoginMutationRequest }, TContext>(
    {
      mutationFn: async ({ data }) => {
        return postApiAuthLogin(data, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}