/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '@/config/axiosClient.ts'
import type { PostApiAuthRegisterMutationRequest, PostApiAuthRegisterMutationResponse } from '../../types/AuthController/PostApiAuthRegister.ts'
import { useMutation } from '@tanstack/react-query'

export const postApiAuthRegisterMutationKey = () => [{ url: '/api/auth/register' }] as const

export type PostApiAuthRegisterMutationKey = ReturnType<typeof postApiAuthRegisterMutationKey>

/**
 * {@link /api/auth/register}
 */
export async function postApiAuthRegister(
  data?: PostApiAuthRegisterMutationRequest,
  config: Partial<RequestConfig<PostApiAuthRegisterMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<PostApiAuthRegisterMutationResponse, ResponseErrorConfig<Error>, PostApiAuthRegisterMutationRequest>({
    method: 'POST',
    url: `/api/auth/register`,
    data,
    ...requestConfig,
    headers: { 'Content-Type': 'application/*+json', ...requestConfig.headers },
  })
  return res
}

/**
 * {@link /api/auth/register}
 */
export function usePostApiAuthRegister<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ResponseConfig<PostApiAuthRegisterMutationResponse>,
      ResponseErrorConfig<Error>,
      { data?: PostApiAuthRegisterMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PostApiAuthRegisterMutationRequest>> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? postApiAuthRegisterMutationKey()

  return useMutation<ResponseConfig<PostApiAuthRegisterMutationResponse>, ResponseErrorConfig<Error>, { data?: PostApiAuthRegisterMutationRequest }, TContext>(
    {
      mutationFn: async ({ data }) => {
        return postApiAuthRegister(data, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}