/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '@/config/axiosClient.ts'
import type { PostApiAuthSetPasswordMutationRequest, PostApiAuthSetPasswordMutationResponse } from '../../types/AuthController/PostApiAuthSetPassword.ts'
import { useMutation } from '@tanstack/react-query'

export const postApiAuthSetPasswordMutationKey = () => [{ url: '/api/auth/set-password' }] as const

export type PostApiAuthSetPasswordMutationKey = ReturnType<typeof postApiAuthSetPasswordMutationKey>

/**
 * {@link /api/auth/set-password}
 */
export async function postApiAuthSetPassword(
  data?: PostApiAuthSetPasswordMutationRequest,
  config: Partial<RequestConfig<PostApiAuthSetPasswordMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<PostApiAuthSetPasswordMutationResponse, ResponseErrorConfig<Error>, PostApiAuthSetPasswordMutationRequest>({
    method: 'POST',
    url: `/api/auth/set-password`,
    data,
    ...requestConfig,
    headers: { 'Content-Type': 'application/*+json', ...requestConfig.headers },
  })
  return res
}

/**
 * {@link /api/auth/set-password}
 */
export function usePostApiAuthSetPassword<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ResponseConfig<PostApiAuthSetPasswordMutationResponse>,
      ResponseErrorConfig<Error>,
      { data?: PostApiAuthSetPasswordMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PostApiAuthSetPasswordMutationRequest>> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? postApiAuthSetPasswordMutationKey()

  return useMutation<
    ResponseConfig<PostApiAuthSetPasswordMutationResponse>,
    ResponseErrorConfig<Error>,
    { data?: PostApiAuthSetPasswordMutationRequest },
    TContext
  >(
    {
      mutationFn: async ({ data }) => {
        return postApiAuthSetPassword(data, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}