/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '@/config/axiosClient.ts'
import type { PostApiAuthResendOtpMutationRequest, PostApiAuthResendOtpMutationResponse } from '../../types/AuthController/PostApiAuthResendOtp.ts'
import { useMutation } from '@tanstack/react-query'

export const postApiAuthResendOtpMutationKey = () => [{ url: '/api/auth/resend-otp' }] as const

export type PostApiAuthResendOtpMutationKey = ReturnType<typeof postApiAuthResendOtpMutationKey>

/**
 * {@link /api/auth/resend-otp}
 */
export async function postApiAuthResendOtp(
  data?: PostApiAuthResendOtpMutationRequest,
  config: Partial<RequestConfig<PostApiAuthResendOtpMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<PostApiAuthResendOtpMutationResponse, ResponseErrorConfig<Error>, PostApiAuthResendOtpMutationRequest>({
    method: 'POST',
    url: `/api/auth/resend-otp`,
    data,
    ...requestConfig,
    headers: { 'Content-Type': 'application/*+json', ...requestConfig.headers },
  })
  return res
}

/**
 * {@link /api/auth/resend-otp}
 */
export function usePostApiAuthResendOtp<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ResponseConfig<PostApiAuthResendOtpMutationResponse>,
      ResponseErrorConfig<Error>,
      { data?: PostApiAuthResendOtpMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PostApiAuthResendOtpMutationRequest>> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? postApiAuthResendOtpMutationKey()

  return useMutation<
    ResponseConfig<PostApiAuthResendOtpMutationResponse>,
    ResponseErrorConfig<Error>,
    { data?: PostApiAuthResendOtpMutationRequest },
    TContext
  >(
    {
      mutationFn: async ({ data }) => {
        return postApiAuthResendOtp(data, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}