/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '@/config/axiosClient.ts'
import type {
  PostApiAuthLoginWithGoogleMutationRequest,
  PostApiAuthLoginWithGoogleMutationResponse,
} from '../../types/AuthController/PostApiAuthLoginWithGoogle.ts'
import { useMutation } from '@tanstack/react-query'

export const postApiAuthLoginWithGoogleMutationKey = () => [{ url: '/api/auth/login-with-google' }] as const

export type PostApiAuthLoginWithGoogleMutationKey = ReturnType<typeof postApiAuthLoginWithGoogleMutationKey>

/**
 * {@link /api/auth/login-with-google}
 */
export async function postApiAuthLoginWithGoogle(
  data?: PostApiAuthLoginWithGoogleMutationRequest,
  config: Partial<RequestConfig<PostApiAuthLoginWithGoogleMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<PostApiAuthLoginWithGoogleMutationResponse, ResponseErrorConfig<Error>, PostApiAuthLoginWithGoogleMutationRequest>({
    method: 'POST',
    url: `/api/auth/login-with-google`,
    data,
    ...requestConfig,
    headers: { 'Content-Type': 'application/*+json', ...requestConfig.headers },
  })
  return res
}

/**
 * {@link /api/auth/login-with-google}
 */
export function usePostApiAuthLoginWithGoogle<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ResponseConfig<PostApiAuthLoginWithGoogleMutationResponse>,
      ResponseErrorConfig<Error>,
      { data?: PostApiAuthLoginWithGoogleMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PostApiAuthLoginWithGoogleMutationRequest>> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? postApiAuthLoginWithGoogleMutationKey()

  return useMutation<
    ResponseConfig<PostApiAuthLoginWithGoogleMutationResponse>,
    ResponseErrorConfig<Error>,
    { data?: PostApiAuthLoginWithGoogleMutationRequest },
    TContext
  >(
    {
      mutationFn: async ({ data }) => {
        return postApiAuthLoginWithGoogle(data, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}