/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteApiTargettabunganResettargetIdtargettabunganPathParams = {
  /**
   * @type integer, int32
   */
  idTargetTabungan: number
}

/**
 * @description OK
 */
export type DeleteApiTargettabunganResettargetIdtargettabungan200 = any

export type DeleteApiTargettabunganResettargetIdtargettabunganMutationResponse = DeleteApiTargettabunganResettargetIdtargettabungan200

export type DeleteApiTargettabunganResettargetIdtargettabunganMutation = {
  Response: DeleteApiTargettabunganResettargetIdtargettabungan200
  PathParams: DeleteApiTargettabunganResettargetIdtargettabunganPathParams
  Errors: any
}