/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetApiTargettabunganIdPathParams = {
  /**
   * @type integer, int32
   */
  id: number
}

/**
 * @description OK
 */
export type GetApiTargettabunganId200 = any

export type GetApiTargettabunganIdQueryResponse = GetApiTargettabunganId200

export type GetApiTargettabunganIdQuery = {
  Response: GetApiTargettabunganId200
  PathParams: GetApiTargettabunganIdPathParams
  Errors: any
}