/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description OK
 */
export type GetApiTargettabungan200 = any

export type GetApiTargettabunganQueryResponse = GetApiTargettabungan200

export type GetApiTargettabunganQuery = {
  Response: GetApiTargettabungan200
  Errors: any
}