/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description OK
 */
export type PostApiTargettabungan200 = any

export type PostApiTargettabunganMutationResponse = PostApiTargettabungan200

export type PostApiTargettabunganMutation = {
  Response: PostApiTargettabungan200
  Errors: any
}