/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description OK
 */
export type PostApiTargettabunganAutodeletetarget200 = any

export type PostApiTargettabunganAutodeletetargetMutationResponse = PostApiTargettabunganAutodeletetarget200

export type PostApiTargettabunganAutodeletetargetMutation = {
  Response: PostApiTargettabunganAutodeletetarget200
  Errors: any
}