/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiOpsibandingQueryResponse, GetApiOpsibandingQueryParams } from '../../types/OpsiBandingController/GetApiOpsibanding.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getApiOpsibandingQueryKey = (params?: GetApiOpsibandingQueryParams) => [{ url: '/api/OpsiBanding' }, ...(params ? [params] : [])] as const

export type GetApiOpsibandingQueryKey = ReturnType<typeof getApiOpsibandingQueryKey>

/**
 * {@link /api/OpsiBanding}
 */
export async function getApiOpsibanding(params?: GetApiOpsibandingQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiOpsibandingQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/OpsiBanding`,
    params,
    ...requestConfig,
  })
  return res
}

export function getApiOpsibandingQueryOptions(params?: GetApiOpsibandingQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiOpsibandingQueryKey(params)
  return queryOptions<
    ResponseConfig<GetApiOpsibandingQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiOpsibandingQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiOpsibanding(params, config)
    },
  })
}

/**
 * {@link /api/OpsiBanding}
 */
export function useGetApiOpsibanding<
  TData = ResponseConfig<GetApiOpsibandingQueryResponse>,
  TQueryData = ResponseConfig<GetApiOpsibandingQueryResponse>,
  TQueryKey extends QueryKey = GetApiOpsibandingQueryKey,
>(
  params?: GetApiOpsibandingQueryParams,
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<GetApiOpsibandingQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiOpsibandingQueryKey(params)

  const query = useQuery(
    {
      ...(getApiOpsibandingQueryOptions(params, config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}