/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiOpsibandingQueryResponse, GetApiOpsibandingQueryParams } from '../../types/OpsiBandingController/GetApiOpsibanding.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getApiOpsibandingSuspenseQueryKey = (params?: GetApiOpsibandingQueryParams) => [{ url: '/api/OpsiBanding' }, ...(params ? [params] : [])] as const

export type GetApiOpsibandingSuspenseQueryKey = ReturnType<typeof getApiOpsibandingSuspenseQueryKey>

/**
 * {@link /api/OpsiBanding}
 */
export async function getApiOpsibandingSuspense(params?: GetApiOpsibandingQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiOpsibandingQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/OpsiBanding`,
    params,
    ...requestConfig,
  })
  return res
}

export function getApiOpsibandingSuspenseQueryOptions(params?: GetApiOpsibandingQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiOpsibandingSuspenseQueryKey(params)
  return queryOptions<
    ResponseConfig<GetApiOpsibandingQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiOpsibandingQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiOpsibandingSuspense(params, config)
    },
  })
}

/**
 * {@link /api/OpsiBanding}
 */
export function useGetApiOpsibandingSuspense<
  TData = ResponseConfig<GetApiOpsibandingQueryResponse>,
  TQueryKey extends QueryKey = GetApiOpsibandingSuspenseQueryKey,
>(
  params?: GetApiOpsibandingQueryParams,
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetApiOpsibandingQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiOpsibandingSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...(getApiOpsibandingSuspenseQueryOptions(params, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}