/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiOpsibandingQueryResponse, GetApiOpsibandingQueryParams } from '../../types/OpsiBandingController/GetApiOpsibanding.ts'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getApiOpsibandingInfiniteQueryKey = (params?: GetApiOpsibandingQueryParams) => [{ url: '/api/OpsiBanding' }, ...(params ? [params] : [])] as const

export type GetApiOpsibandingInfiniteQueryKey = ReturnType<typeof getApiOpsibandingInfiniteQueryKey>

/**
 * {@link /api/OpsiBanding}
 */
export async function getApiOpsibandingInfinite(params?: GetApiOpsibandingQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiOpsibandingQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/OpsiBanding`,
    params,
    ...requestConfig,
  })
  return res
}

export function getApiOpsibandingInfiniteQueryOptions(params?: GetApiOpsibandingQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiOpsibandingInfiniteQueryKey(params)
  return infiniteQueryOptions<
    ResponseConfig<GetApiOpsibandingQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiOpsibandingQueryResponse>,
    typeof queryKey,
    number
  >({
    queryKey,
    queryFn: async ({ signal, pageParam }) => {
      config.signal = signal

      if (params) {
        params['next_page'] = pageParam as unknown as GetApiOpsibandingQueryParams['next_page']
      }
      return getApiOpsibandingInfinite(params, config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * {@link /api/OpsiBanding}
 */
export function useGetApiOpsibandingInfinite<
  TData = InfiniteData<ResponseConfig<GetApiOpsibandingQueryResponse>>,
  TQueryData = ResponseConfig<GetApiOpsibandingQueryResponse>,
  TQueryKey extends QueryKey = GetApiOpsibandingInfiniteQueryKey,
>(
  params?: GetApiOpsibandingQueryParams,
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetApiOpsibandingQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiOpsibandingInfiniteQueryKey(params)

  const query = useInfiniteQuery(
    {
      ...(getApiOpsibandingInfiniteQueryOptions(params, config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}