/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiSmartassistantSaranQueryResponse } from '../../types/SmartAssistantController/GetApiSmartassistantSaran.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getApiSmartassistantSaranSuspenseQueryKey = () => [{ url: '/api/SmartAssistant/saran' }] as const

export type GetApiSmartassistantSaranSuspenseQueryKey = ReturnType<typeof getApiSmartassistantSaranSuspenseQueryKey>

/**
 * {@link /api/SmartAssistant/saran}
 */
export async function getApiSmartassistantSaranSuspense(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiSmartassistantSaranQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/SmartAssistant/saran`,
    ...requestConfig,
  })
  return res
}

export function getApiSmartassistantSaranSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiSmartassistantSaranSuspenseQueryKey()
  return queryOptions<
    ResponseConfig<GetApiSmartassistantSaranQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiSmartassistantSaranQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiSmartassistantSaranSuspense(config)
    },
  })
}

/**
 * {@link /api/SmartAssistant/saran}
 */
export function useGetApiSmartassistantSaranSuspense<
  TData = ResponseConfig<GetApiSmartassistantSaranQueryResponse>,
  TQueryKey extends QueryKey = GetApiSmartassistantSaranSuspenseQueryKey,
>(
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetApiSmartassistantSaranQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiSmartassistantSaranSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...(getApiSmartassistantSaranSuspenseQueryOptions(config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}