/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiSmartassistantSaranQueryResponse } from '../../types/SmartAssistantController/GetApiSmartassistantSaran.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getApiSmartassistantSaranQueryKey = () => [{ url: '/api/SmartAssistant/saran' }] as const

export type GetApiSmartassistantSaranQueryKey = ReturnType<typeof getApiSmartassistantSaranQueryKey>

/**
 * {@link /api/SmartAssistant/saran}
 */
export async function getApiSmartassistantSaran(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiSmartassistantSaranQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/SmartAssistant/saran`,
    ...requestConfig,
  })
  return res
}

export function getApiSmartassistantSaranQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiSmartassistantSaranQueryKey()
  return queryOptions<
    ResponseConfig<GetApiSmartassistantSaranQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiSmartassistantSaranQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiSmartassistantSaran(config)
    },
  })
}

/**
 * {@link /api/SmartAssistant/saran}
 */
export function useGetApiSmartassistantSaran<
  TData = ResponseConfig<GetApiSmartassistantSaranQueryResponse>,
  TQueryData = ResponseConfig<GetApiSmartassistantSaranQueryResponse>,
  TQueryKey extends QueryKey = GetApiSmartassistantSaranQueryKey,
>(
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<GetApiSmartassistantSaranQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiSmartassistantSaranQueryKey()

  const query = useQuery(
    {
      ...(getApiSmartassistantSaranQueryOptions(config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}