/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiSmartassistantSaranQueryResponse } from '../../types/SmartAssistantController/GetApiSmartassistantSaran.ts'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getApiSmartassistantSaranInfiniteQueryKey = () => [{ url: '/api/SmartAssistant/saran' }] as const

export type GetApiSmartassistantSaranInfiniteQueryKey = ReturnType<typeof getApiSmartassistantSaranInfiniteQueryKey>

/**
 * {@link /api/SmartAssistant/saran}
 */
export async function getApiSmartassistantSaranInfinite(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiSmartassistantSaranQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/SmartAssistant/saran`,
    ...requestConfig,
  })
  return res
}

export function getApiSmartassistantSaranInfiniteQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiSmartassistantSaranInfiniteQueryKey()
  return infiniteQueryOptions<
    ResponseConfig<GetApiSmartassistantSaranQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiSmartassistantSaranQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiSmartassistantSaranInfinite(config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * {@link /api/SmartAssistant/saran}
 */
export function useGetApiSmartassistantSaranInfinite<
  TData = InfiniteData<ResponseConfig<GetApiSmartassistantSaranQueryResponse>>,
  TQueryData = ResponseConfig<GetApiSmartassistantSaranQueryResponse>,
  TQueryKey extends QueryKey = GetApiSmartassistantSaranInfiniteQueryKey,
>(
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetApiSmartassistantSaranQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiSmartassistantSaranInfiniteQueryKey()

  const query = useInfiniteQuery(
    {
      ...(getApiSmartassistantSaranInfiniteQueryOptions(config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}