/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreatePemasukanDto = {
  /**
   * @type string | undefined, date-time
   */
  tanggal?: string
  /**
   * @type string
   */
  deskripsi?: string | null
  /**
   * @type number | undefined, double
   */
  jumlah?: number
}