/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateTargetTabunganRequest = {
  /**
   * @type string
   */
  namaTarget?: string | null
  /**
   * @type string
   */
  deskripsi?: string | null
  /**
   * @type number | undefined, double
   */
  nominalTarget?: number
  /**
   * @type string, date-time
   */
  tanggalTarget?: string | null
  /**
   * @type string
   */
  gambar?: string | null
}