/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type KategoriTerbesarDto = {
  /**
   * @type string
   */
  namaKategori?: string | null
  /**
   * @type number | undefined, double
   */
  persentaseKategori?: number
}