/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type LoginDto = {
  /**
   * @type string
   */
  identifier?: string | null
  /**
   * @type string
   */
  password?: string | null
}