/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type OpsiBandingCreateDto = {
  /**
   * @type integer | undefined, int32
   */
  idRencanaBanding?: number
  /**
   * @type string
   */
  namaOpsi?: string | null
  /**
   * @type number | undefined, double
   */
  estimasiBiaya?: number
  /**
   * @type string
   */
  namaKategori?: string | null
}