/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type OTP = {
  /**
   * @type string
   */
  email?: string | null
  /**
   * @type string
   */
  otp?: string | null
}