/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PengeluaranGetDto = {
  /**
   * @type integer | undefined, int32
   */
  idPengeluaran?: number
  /**
   * @type string | undefined, date
   */
  tanggal?: string
  /**
   * @type string
   */
  deskripsi?: string | null
  /**
   * @type number | undefined, double
   */
  nominal?: number
  /**
   * @type integer | undefined, int32
   */
  idKategoriPengeluaran?: number
  /**
   * @type string
   */
  namaKategori?: string | null
  /**
   * @type string | undefined, date-time
   */
  createdAt?: string
  /**
   * @type string | undefined, date-time
   */
  updatedAt?: string
  /**
   * @type integer, int32
   */
  idTargetTabungan?: number | null
  /**
   * @type string
   */
  namaTarget?: string | null
}