/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { KategoriTerbesarDto } from './KategoriTerbesarDto.ts'

export type PengeluaranPerTahunDto = {
  /**
   * @type integer | undefined, int32
   */
  tahun?: number
  /**
   * @type number | undefined, double
   */
  persentasePengeluaran?: number
  /**
   * @type number | undefined, double
   */
  totalPengeluaran?: number
  /**
   * @type object | undefined
   */
  kategoriTerbesar?: KategoriTerbesarDto
}