/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PengeluaranPerKategoriDto = {
  /**
   * @type string
   */
  namaKategori?: string | null
  /**
   * @type number | undefined, double
   */
  totalPengeluaranKategori?: number
  /**
   * @type number | undefined, double
   */
  persentasePengeluaran?: number
}