/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PengeluaranPerKategoriDto } from './PengeluaranPerKategoriDto.ts'

export type PengeluaranPerBulanDto = {
  /**
   * @type integer | undefined, int32
   */
  bulan?: number
  /**
   * @type number | undefined, double
   */
  totalPengeluaran?: number
  /**
   * @type array
   */
  kategoriPengeluaran?: PengeluaranPerKategoriDto[] | null
}