/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PengeluaranCreateDto = {
  /**
   * @type string
   */
  deskripsi?: string | null
  /**
   * @type number | undefined, double
   */
  nominal?: number
  /**
   * @type string
   */
  namaKategori?: string | null
}