/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { OpsiBandingCreateDto } from './OpsiBandingCreateDto.ts'

export type RencanaBandingCreateDto = {
  /**
   * @type string
   */
  namaRencana?: string | null
  /**
   * @type string | undefined, date-time
   */
  tanggalRencana?: string
  /**
   * @type array
   */
  opsiBanding?: OpsiBandingCreateDto[] | null
}