/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type RestPassword = {
  /**
   * @type string
   */
  email?: string | null
  /**
   * @type string
   */
  password?: string | null
}