/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiTargettabunganIdQueryResponse, GetApiTargettabunganIdPathParams } from '../../types/TargetTabunganController/GetApiTargettabunganId.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getApiTargettabunganIdSuspenseQueryKey = (id: GetApiTargettabunganIdPathParams['id']) =>
  [{ url: '/api/TargetTabungan/:id', params: { id: id } }] as const

export type GetApiTargettabunganIdSuspenseQueryKey = ReturnType<typeof getApiTargettabunganIdSuspenseQueryKey>

/**
 * {@link /api/TargetTabungan/:id}
 */
export async function getApiTargettabunganIdSuspense(
  id: GetApiTargettabunganIdPathParams['id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiTargettabunganIdQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/TargetTabungan/${id}`,
    ...requestConfig,
  })
  return res
}

export function getApiTargettabunganIdSuspenseQueryOptions(
  id: GetApiTargettabunganIdPathParams['id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = getApiTargettabunganIdSuspenseQueryKey(id)
  return queryOptions<
    ResponseConfig<GetApiTargettabunganIdQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiTargettabunganIdQueryResponse>,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiTargettabunganIdSuspense(id, config)
    },
  })
}

/**
 * {@link /api/TargetTabungan/:id}
 */
export function useGetApiTargettabunganIdSuspense<
  TData = ResponseConfig<GetApiTargettabunganIdQueryResponse>,
  TQueryKey extends QueryKey = GetApiTargettabunganIdSuspenseQueryKey,
>(
  id: GetApiTargettabunganIdPathParams['id'],
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetApiTargettabunganIdQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiTargettabunganIdSuspenseQueryKey(id)

  const query = useSuspenseQuery(
    {
      ...(getApiTargettabunganIdSuspenseQueryOptions(id, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}