/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiTargettabunganQueryResponse } from '../../types/TargetTabunganController/GetApiTargettabungan.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getApiTargettabunganSuspenseQueryKey = () => [{ url: '/api/TargetTabungan' }] as const

export type GetApiTargettabunganSuspenseQueryKey = ReturnType<typeof getApiTargettabunganSuspenseQueryKey>

/**
 * {@link /api/TargetTabungan}
 */
export async function getApiTargettabunganSuspense(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiTargettabunganQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/TargetTabungan`,
    ...requestConfig,
  })
  return res
}

export function getApiTargettabunganSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiTargettabunganSuspenseQueryKey()
  return queryOptions<
    ResponseConfig<GetApiTargettabunganQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiTargettabunganQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiTargettabunganSuspense(config)
    },
  })
}

/**
 * {@link /api/TargetTabungan}
 */
export function useGetApiTargettabunganSuspense<
  TData = ResponseConfig<GetApiTargettabunganQueryResponse>,
  TQueryKey extends QueryKey = GetApiTargettabunganSuspenseQueryKey,
>(
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetApiTargettabunganQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiTargettabunganSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...(getApiTargettabunganSuspenseQueryOptions(config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}