/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiTargettabunganQueryResponse } from '../../types/TargetTabunganController/GetApiTargettabungan.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getApiTargettabunganQueryKey = () => [{ url: '/api/TargetTabungan' }] as const

export type GetApiTargettabunganQueryKey = ReturnType<typeof getApiTargettabunganQueryKey>

/**
 * {@link /api/TargetTabungan}
 */
export async function getApiTargettabungan(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiTargettabunganQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/TargetTabungan`,
    ...requestConfig,
  })
  return res
}

export function getApiTargettabunganQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiTargettabunganQueryKey()
  return queryOptions<
    ResponseConfig<GetApiTargettabunganQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiTargettabunganQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiTargettabungan(config)
    },
  })
}

/**
 * {@link /api/TargetTabungan}
 */
export function useGetApiTargettabungan<
  TData = ResponseConfig<GetApiTargettabunganQueryResponse>,
  TQueryData = ResponseConfig<GetApiTargettabunganQueryResponse>,
  TQueryKey extends QueryKey = GetApiTargettabunganQueryKey,
>(
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<GetApiTargettabunganQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiTargettabunganQueryKey()

  const query = useQuery(
    {
      ...(getApiTargettabunganQueryOptions(config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}