/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiTargettabunganIdQueryResponse, GetApiTargettabunganIdPathParams } from '../../types/TargetTabunganController/GetApiTargettabunganId.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getApiTargettabunganIdQueryKey = (id: GetApiTargettabunganIdPathParams['id']) => [{ url: '/api/TargetTabungan/:id', params: { id: id } }] as const

export type GetApiTargettabunganIdQueryKey = ReturnType<typeof getApiTargettabunganIdQueryKey>

/**
 * {@link /api/TargetTabungan/:id}
 */
export async function getApiTargettabunganId(id: GetApiTargettabunganIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiTargettabunganIdQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/TargetTabungan/${id}`,
    ...requestConfig,
  })
  return res
}

export function getApiTargettabunganIdQueryOptions(
  id: GetApiTargettabunganIdPathParams['id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = getApiTargettabunganIdQueryKey(id)
  return queryOptions<
    ResponseConfig<GetApiTargettabunganIdQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiTargettabunganIdQueryResponse>,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiTargettabunganId(id, config)
    },
  })
}

/**
 * {@link /api/TargetTabungan/:id}
 */
export function useGetApiTargettabunganId<
  TData = ResponseConfig<GetApiTargettabunganIdQueryResponse>,
  TQueryData = ResponseConfig<GetApiTargettabunganIdQueryResponse>,
  TQueryKey extends QueryKey = GetApiTargettabunganIdQueryKey,
>(
  id: GetApiTargettabunganIdPathParams['id'],
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<GetApiTargettabunganIdQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiTargettabunganIdQueryKey(id)

  const query = useQuery(
    {
      ...(getApiTargettabunganIdQueryOptions(id, config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}