/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '@/config/axiosClient.ts'
import type { PostApiTargettabunganAutodeletetargetMutationResponse } from '../../types/TargetTabunganController/PostApiTargettabunganAutodeletetarget.ts'
import { useMutation } from '@tanstack/react-query'

export const postApiTargettabunganAutodeletetargetMutationKey = () => [{ url: '/api/TargetTabungan/AutoDeleteTarget' }] as const

export type PostApiTargettabunganAutodeletetargetMutationKey = ReturnType<typeof postApiTargettabunganAutodeletetargetMutationKey>

/**
 * {@link /api/TargetTabungan/AutoDeleteTarget}
 */
export async function postApiTargettabunganAutodeletetarget(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<PostApiTargettabunganAutodeletetargetMutationResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'POST',
    url: `/api/TargetTabungan/AutoDeleteTarget`,
    ...requestConfig,
  })
  return res
}

/**
 * {@link /api/TargetTabungan/AutoDeleteTarget}
 */
export function usePostApiTargettabunganAutodeletetarget<TContext>(
  options: {
    mutation?: UseMutationOptions<ResponseConfig<PostApiTargettabunganAutodeletetargetMutationResponse>, ResponseErrorConfig<Error>, void, TContext> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? postApiTargettabunganAutodeletetargetMutationKey()

  return useMutation<ResponseConfig<PostApiTargettabunganAutodeletetargetMutationResponse>, ResponseErrorConfig<Error>, void, TContext>(
    {
      mutationFn: async () => {
        return postApiTargettabunganAutodeletetarget(config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}