/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '@/config/axiosClient.ts'
import type {
  DeleteApiRencanabandingIdMutationResponse,
  DeleteApiRencanabandingIdPathParams,
} from '../../types/RencanaBandingController/DeleteApiRencanabandingId.ts'
import { useMutation } from '@tanstack/react-query'

export const deleteApiRencanabandingIdMutationKey = () => [{ url: '/api/RencanaBanding/{id}' }] as const

export type DeleteApiRencanabandingIdMutationKey = ReturnType<typeof deleteApiRencanabandingIdMutationKey>

/**
 * {@link /api/RencanaBanding/:id}
 */
export async function deleteApiRencanabandingId(
  id: DeleteApiRencanabandingIdPathParams['id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<DeleteApiRencanabandingIdMutationResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'DELETE',
    url: `/api/RencanaBanding/${id}`,
    ...requestConfig,
  })
  return res
}

/**
 * {@link /api/RencanaBanding/:id}
 */
export function useDeleteApiRencanabandingId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ResponseConfig<DeleteApiRencanabandingIdMutationResponse>,
      ResponseErrorConfig<Error>,
      { id: DeleteApiRencanabandingIdPathParams['id'] },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? deleteApiRencanabandingIdMutationKey()

  return useMutation<
    ResponseConfig<DeleteApiRencanabandingIdMutationResponse>,
    ResponseErrorConfig<Error>,
    { id: DeleteApiRencanabandingIdPathParams['id'] },
    TContext
  >(
    {
      mutationFn: async ({ id }) => {
        return deleteApiRencanabandingId(id, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}