/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiRencanabandingQueryResponse } from '../../types/RencanaBandingController/GetApiRencanabanding.ts'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getApiRencanabandingInfiniteQueryKey = () => [{ url: '/api/RencanaBanding' }] as const

export type GetApiRencanabandingInfiniteQueryKey = ReturnType<typeof getApiRencanabandingInfiniteQueryKey>

/**
 * {@link /api/RencanaBanding}
 */
export async function getApiRencanabandingInfinite(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiRencanabandingQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/RencanaBanding`,
    ...requestConfig,
  })
  return res
}

export function getApiRencanabandingInfiniteQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiRencanabandingInfiniteQueryKey()
  return infiniteQueryOptions<
    ResponseConfig<GetApiRencanabandingQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiRencanabandingQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiRencanabandingInfinite(config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * {@link /api/RencanaBanding}
 */
export function useGetApiRencanabandingInfinite<
  TData = InfiniteData<ResponseConfig<GetApiRencanabandingQueryResponse>>,
  TQueryData = ResponseConfig<GetApiRencanabandingQueryResponse>,
  TQueryKey extends QueryKey = GetApiRencanabandingInfiniteQueryKey,
>(
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetApiRencanabandingQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiRencanabandingInfiniteQueryKey()

  const query = useInfiniteQuery(
    {
      ...(getApiRencanabandingInfiniteQueryOptions(config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}