/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiRencanabandingQueryResponse } from '../../types/RencanaBandingController/GetApiRencanabanding.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getApiRencanabandingQueryKey = () => [{ url: '/api/RencanaBanding' }] as const

export type GetApiRencanabandingQueryKey = ReturnType<typeof getApiRencanabandingQueryKey>

/**
 * {@link /api/RencanaBanding}
 */
export async function getApiRencanabanding(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiRencanabandingQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/RencanaBanding`,
    ...requestConfig,
  })
  return res
}

export function getApiRencanabandingQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiRencanabandingQueryKey()
  return queryOptions<
    ResponseConfig<GetApiRencanabandingQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiRencanabandingQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiRencanabanding(config)
    },
  })
}

/**
 * {@link /api/RencanaBanding}
 */
export function useGetApiRencanabanding<
  TData = ResponseConfig<GetApiRencanabandingQueryResponse>,
  TQueryData = ResponseConfig<GetApiRencanabandingQueryResponse>,
  TQueryKey extends QueryKey = GetApiRencanabandingQueryKey,
>(
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<GetApiRencanabandingQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiRencanabandingQueryKey()

  const query = useQuery(
    {
      ...(getApiRencanabandingQueryOptions(config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}