/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiRencanabandingQueryResponse } from '../../types/RencanaBandingController/GetApiRencanabanding.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getApiRencanabandingSuspenseQueryKey = () => [{ url: '/api/RencanaBanding' }] as const

export type GetApiRencanabandingSuspenseQueryKey = ReturnType<typeof getApiRencanabandingSuspenseQueryKey>

/**
 * {@link /api/RencanaBanding}
 */
export async function getApiRencanabandingSuspense(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiRencanabandingQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/RencanaBanding`,
    ...requestConfig,
  })
  return res
}

export function getApiRencanabandingSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiRencanabandingSuspenseQueryKey()
  return queryOptions<
    ResponseConfig<GetApiRencanabandingQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiRencanabandingQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiRencanabandingSuspense(config)
    },
  })
}

/**
 * {@link /api/RencanaBanding}
 */
export function useGetApiRencanabandingSuspense<
  TData = ResponseConfig<GetApiRencanabandingQueryResponse>,
  TQueryKey extends QueryKey = GetApiRencanabandingSuspenseQueryKey,
>(
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetApiRencanabandingQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiRencanabandingSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...(getApiRencanabandingSuspenseQueryOptions(config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}