/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '@/config/axiosClient.ts'
import type { PostApiRencanabandingMutationRequest, PostApiRencanabandingMutationResponse } from '../../types/RencanaBandingController/PostApiRencanabanding.ts'
import { useMutation } from '@tanstack/react-query'

export const postApiRencanabandingMutationKey = () => [{ url: '/api/RencanaBanding' }] as const

export type PostApiRencanabandingMutationKey = ReturnType<typeof postApiRencanabandingMutationKey>

/**
 * {@link /api/RencanaBanding}
 */
export async function postApiRencanabanding(
  data?: PostApiRencanabandingMutationRequest,
  config: Partial<RequestConfig<PostApiRencanabandingMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<PostApiRencanabandingMutationResponse, ResponseErrorConfig<Error>, PostApiRencanabandingMutationRequest>({
    method: 'POST',
    url: `/api/RencanaBanding`,
    data,
    ...requestConfig,
    headers: { 'Content-Type': 'application/*+json', ...requestConfig.headers },
  })
  return res
}

/**
 * {@link /api/RencanaBanding}
 */
export function usePostApiRencanabanding<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ResponseConfig<PostApiRencanabandingMutationResponse>,
      ResponseErrorConfig<Error>,
      { data?: PostApiRencanabandingMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PostApiRencanabandingMutationRequest>> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? postApiRencanabandingMutationKey()

  return useMutation<
    ResponseConfig<PostApiRencanabandingMutationResponse>,
    ResponseErrorConfig<Error>,
    { data?: PostApiRencanabandingMutationRequest },
    TContext
  >(
    {
      mutationFn: async ({ data }) => {
        return postApiRencanabanding(data, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}