/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetApiSetoranListQueryParams = {
  /**
   * @type integer | undefined, int32
   */
  idTargetTabungan?: number
}

/**
 * @description OK
 */
export type GetApiSetoranList200 = any

export type GetApiSetoranListQueryResponse = GetApiSetoranList200

export type GetApiSetoranListQuery = {
  Response: GetApiSetoranList200
  QueryParams: GetApiSetoranListQueryParams
  Errors: any
}