/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateSetoranRequest } from '../CreateSetoranRequest.ts'

export type PostApiSetoranSetorQueryParams = {
  /**
   * @type string | undefined
   */
  namaTarget?: string
}

/**
 * @description OK
 */
export type PostApiSetoranSetor200 = any

export type PostApiSetoranSetorMutationRequest = CreateSetoranRequest

export type PostApiSetoranSetorMutationResponse = PostApiSetoranSetor200

export type PostApiSetoranSetorMutation = {
  Response: PostApiSetoranSetor200
  Request: PostApiSetoranSetorMutationRequest
  QueryParams: PostApiSetoranSetorQueryParams
  Errors: any
}