/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description OK
 */
export type GetApiUsers200 = any

export type GetApiUsersQueryResponse = GetApiUsers200

export type GetApiUsersQuery = {
  Response: GetApiUsers200
  Errors: any
}