/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description OK
 */
export type GetApiAuthProtectedEndpoint200 = any

export type GetApiAuthProtectedEndpointQueryResponse = GetApiAuthProtectedEndpoint200

export type GetApiAuthProtectedEndpointQuery = {
  Response: GetApiAuthProtectedEndpoint200
  Errors: any
}