/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description OK
 */
export type GetApiAuthCheckAuth200 = any

export type GetApiAuthCheckAuthQueryResponse = GetApiAuthCheckAuth200

export type GetApiAuthCheckAuthQuery = {
  Response: GetApiAuthCheckAuth200
  Errors: any
}