/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResetPasswordRequestDto } from '../ResetPasswordRequestDto.ts'

/**
 * @description OK
 */
export type PostApiAuthResetPasswordRequest200 = any

export type PostApiAuthResetPasswordRequestMutationRequest = ResetPasswordRequestDto

export type PostApiAuthResetPasswordRequestMutationResponse = PostApiAuthResetPasswordRequest200

export type PostApiAuthResetPasswordRequestMutation = {
  Response: PostApiAuthResetPasswordRequest200
  Request: PostApiAuthResetPasswordRequestMutationRequest
  Errors: any
}