/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ForgotPasswordDto } from '../ForgotPasswordDto.ts'

/**
 * @description OK
 */
export type PostApiAuthForgotPassword200 = any

export type PostApiAuthForgotPasswordMutationRequest = ForgotPasswordDto

export type PostApiAuthForgotPasswordMutationResponse = PostApiAuthForgotPassword200

export type PostApiAuthForgotPasswordMutation = {
  Response: PostApiAuthForgotPassword200
  Request: PostApiAuthForgotPasswordMutationRequest
  Errors: any
}