/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RestPassword } from '../RestPassword.ts'

/**
 * @description OK
 */
export type PostApiAuthSetPassword200 = any

export type PostApiAuthSetPasswordMutationRequest = RestPassword

export type PostApiAuthSetPasswordMutationResponse = PostApiAuthSetPassword200

export type PostApiAuthSetPasswordMutation = {
  Response: PostApiAuthSetPassword200
  Request: PostApiAuthSetPasswordMutationRequest
  Errors: any
}