/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { LoginDto } from '../LoginDto.ts'

/**
 * @description OK
 */
export type PostApiAuthLogin200 = any

export type PostApiAuthLoginMutationRequest = LoginDto

export type PostApiAuthLoginMutationResponse = PostApiAuthLogin200

export type PostApiAuthLoginMutation = {
  Response: PostApiAuthLogin200
  Request: PostApiAuthLoginMutationRequest
  Errors: any
}