/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { OTP } from '../OTP.ts'

/**
 * @description OK
 */
export type PostApiAuthVerifyOtp200 = any

export type PostApiAuthVerifyOtpMutationRequest = OTP

export type PostApiAuthVerifyOtpMutationResponse = PostApiAuthVerifyOtp200

export type PostApiAuthVerifyOtpMutation = {
  Response: PostApiAuthVerifyOtp200
  Request: PostApiAuthVerifyOtpMutationRequest
  Errors: any
}