/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GoogleLoginDto } from '../GoogleLoginDto.ts'

/**
 * @description OK
 */
export type PostApiAuthGoogleLogin200 = any

export type PostApiAuthGoogleLoginMutationRequest = GoogleLoginDto

export type PostApiAuthGoogleLoginMutationResponse = PostApiAuthGoogleLogin200

export type PostApiAuthGoogleLoginMutation = {
  Response: PostApiAuthGoogleLogin200
  Request: PostApiAuthGoogleLoginMutationRequest
  Errors: any
}