/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UserRegisterDto } from '../UserRegisterDto.ts'

/**
 * @description OK
 */
export type PostApiAuthRegister200 = any

export type PostApiAuthRegisterMutationRequest = UserRegisterDto

export type PostApiAuthRegisterMutationResponse = PostApiAuthRegister200

export type PostApiAuthRegisterMutation = {
  Response: PostApiAuthRegister200
  Request: PostApiAuthRegisterMutationRequest
  Errors: any
}