/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Auth0LoginDto } from '../Auth0LoginDto.ts'

/**
 * @description OK
 */
export type PostApiAuthAuth0Login200 = any

export type PostApiAuthAuth0LoginMutationRequest = Auth0LoginDto

export type PostApiAuthAuth0LoginMutationResponse = PostApiAuthAuth0Login200

export type PostApiAuthAuth0LoginMutation = {
  Response: PostApiAuthAuth0Login200
  Request: PostApiAuthAuth0LoginMutationRequest
  Errors: any
}