/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResetPasswordRequestDto } from '../ResetPasswordRequestDto.ts'

/**
 * @description OK
 */
export type PostApiAuthResendOtp200 = any

export type PostApiAuthResendOtpMutationRequest = ResetPasswordRequestDto

export type PostApiAuthResendOtpMutationResponse = PostApiAuthResendOtp200

export type PostApiAuthResendOtpMutation = {
  Response: PostApiAuthResendOtp200
  Request: PostApiAuthResendOtpMutationRequest
  Errors: any
}