/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description OK
 */
export type PostApiAuthLoginWithGoogle200 = any

export type PostApiAuthLoginWithGoogleMutationRequest = string

export type PostApiAuthLoginWithGoogleMutationResponse = PostApiAuthLoginWithGoogle200

export type PostApiAuthLoginWithGoogleMutation = {
  Response: PostApiAuthLoginWithGoogle200
  Request: PostApiAuthLoginWithGoogleMutationRequest
  Errors: any
}