/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiPemasukanSaldoQueryResponse } from '../../types/PemasukanController/GetApiPemasukanSaldo.ts'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getApiPemasukanSaldoInfiniteQueryKey = () => [{ url: '/api/Pemasukan/saldo' }] as const

export type GetApiPemasukanSaldoInfiniteQueryKey = ReturnType<typeof getApiPemasukanSaldoInfiniteQueryKey>

/**
 * {@link /api/Pemasukan/saldo}
 */
export async function getApiPemasukanSaldoInfinite(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiPemasukanSaldoQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/Pemasukan/saldo`,
    ...requestConfig,
  })
  return res
}

export function getApiPemasukanSaldoInfiniteQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiPemasukanSaldoInfiniteQueryKey()
  return infiniteQueryOptions<
    ResponseConfig<GetApiPemasukanSaldoQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiPemasukanSaldoQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiPemasukanSaldoInfinite(config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * {@link /api/Pemasukan/saldo}
 */
export function useGetApiPemasukanSaldoInfinite<
  TData = InfiniteData<ResponseConfig<GetApiPemasukanSaldoQueryResponse>>,
  TQueryData = ResponseConfig<GetApiPemasukanSaldoQueryResponse>,
  TQueryKey extends QueryKey = GetApiPemasukanSaldoInfiniteQueryKey,
>(
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetApiPemasukanSaldoQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiPemasukanSaldoInfiniteQueryKey()

  const query = useInfiniteQuery(
    {
      ...(getApiPemasukanSaldoInfiniteQueryOptions(config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}