/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type {
  GetApiPemasukanTotalPemasukanBulanQueryResponse,
  GetApiPemasukanTotalPemasukanBulanQueryParams,
} from '../../types/PemasukanController/GetApiPemasukanTotalPemasukanBulan.ts'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getApiPemasukanTotalPemasukanBulanInfiniteQueryKey = (params?: GetApiPemasukanTotalPemasukanBulanQueryParams) =>
  [{ url: '/api/Pemasukan/total-pemasukan-bulan' }, ...(params ? [params] : [])] as const

export type GetApiPemasukanTotalPemasukanBulanInfiniteQueryKey = ReturnType<typeof getApiPemasukanTotalPemasukanBulanInfiniteQueryKey>

/**
 * {@link /api/Pemasukan/total-pemasukan-bulan}
 */
export async function getApiPemasukanTotalPemasukanBulanInfinite(
  params?: GetApiPemasukanTotalPemasukanBulanQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiPemasukanTotalPemasukanBulanQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/Pemasukan/total-pemasukan-bulan`,
    params,
    ...requestConfig,
  })
  return res
}

export function getApiPemasukanTotalPemasukanBulanInfiniteQueryOptions(
  params?: GetApiPemasukanTotalPemasukanBulanQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = getApiPemasukanTotalPemasukanBulanInfiniteQueryKey(params)
  return infiniteQueryOptions<
    ResponseConfig<GetApiPemasukanTotalPemasukanBulanQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiPemasukanTotalPemasukanBulanQueryResponse>,
    typeof queryKey,
    number
  >({
    queryKey,
    queryFn: async ({ signal, pageParam }) => {
      config.signal = signal

      if (params) {
        params['next_page'] = pageParam as unknown as GetApiPemasukanTotalPemasukanBulanQueryParams['next_page']
      }
      return getApiPemasukanTotalPemasukanBulanInfinite(params, config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * {@link /api/Pemasukan/total-pemasukan-bulan}
 */
export function useGetApiPemasukanTotalPemasukanBulanInfinite<
  TData = InfiniteData<ResponseConfig<GetApiPemasukanTotalPemasukanBulanQueryResponse>>,
  TQueryData = ResponseConfig<GetApiPemasukanTotalPemasukanBulanQueryResponse>,
  TQueryKey extends QueryKey = GetApiPemasukanTotalPemasukanBulanInfiniteQueryKey,
>(
  params?: GetApiPemasukanTotalPemasukanBulanQueryParams,
  options: {
    query?: Partial<
      InfiniteQueryObserverOptions<ResponseConfig<GetApiPemasukanTotalPemasukanBulanQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiPemasukanTotalPemasukanBulanInfiniteQueryKey(params)

  const query = useInfiniteQuery(
    {
      ...(getApiPemasukanTotalPemasukanBulanInfiniteQueryOptions(params, config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}