/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiPemasukanTotalPemasukanBulanIniQueryResponse } from '../../types/PemasukanController/GetApiPemasukanTotalPemasukanBulanIni.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getApiPemasukanTotalPemasukanBulanIniQueryKey = () => [{ url: '/api/Pemasukan/total-pemasukan-bulan-ini' }] as const

export type GetApiPemasukanTotalPemasukanBulanIniQueryKey = ReturnType<typeof getApiPemasukanTotalPemasukanBulanIniQueryKey>

/**
 * {@link /api/Pemasukan/total-pemasukan-bulan-ini}
 */
export async function getApiPemasukanTotalPemasukanBulanIni(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiPemasukanTotalPemasukanBulanIniQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/Pemasukan/total-pemasukan-bulan-ini`,
    ...requestConfig,
  })
  return res
}

export function getApiPemasukanTotalPemasukanBulanIniQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiPemasukanTotalPemasukanBulanIniQueryKey()
  return queryOptions<
    ResponseConfig<GetApiPemasukanTotalPemasukanBulanIniQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiPemasukanTotalPemasukanBulanIniQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiPemasukanTotalPemasukanBulanIni(config)
    },
  })
}

/**
 * {@link /api/Pemasukan/total-pemasukan-bulan-ini}
 */
export function useGetApiPemasukanTotalPemasukanBulanIni<
  TData = ResponseConfig<GetApiPemasukanTotalPemasukanBulanIniQueryResponse>,
  TQueryData = ResponseConfig<GetApiPemasukanTotalPemasukanBulanIniQueryResponse>,
  TQueryKey extends QueryKey = GetApiPemasukanTotalPemasukanBulanIniQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<ResponseConfig<GetApiPemasukanTotalPemasukanBulanIniQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiPemasukanTotalPemasukanBulanIniQueryKey()

  const query = useQuery(
    {
      ...(getApiPemasukanTotalPemasukanBulanIniQueryOptions(config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}