/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiPemasukanQueryResponse } from '../../types/PemasukanController/GetApiPemasukan.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getApiPemasukanSuspenseQueryKey = () => [{ url: '/api/Pemasukan' }] as const

export type GetApiPemasukanSuspenseQueryKey = ReturnType<typeof getApiPemasukanSuspenseQueryKey>

/**
 * {@link /api/Pemasukan}
 */
export async function getApiPemasukanSuspense(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiPemasukanQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/api/Pemasukan`, ...requestConfig })
  return res
}

export function getApiPemasukanSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiPemasukanSuspenseQueryKey()
  return queryOptions<ResponseConfig<GetApiPemasukanQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetApiPemasukanQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiPemasukanSuspense(config)
    },
  })
}

/**
 * {@link /api/Pemasukan}
 */
export function useGetApiPemasukanSuspense<TData = ResponseConfig<GetApiPemasukanQueryResponse>, TQueryKey extends QueryKey = GetApiPemasukanSuspenseQueryKey>(
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetApiPemasukanQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiPemasukanSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...(getApiPemasukanSuspenseQueryOptions(config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}