/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type {
  GetApiPemasukanTotalPemasukanPerTahunQueryResponse,
  GetApiPemasukanTotalPemasukanPerTahunQueryParams,
} from '../../types/PemasukanController/GetApiPemasukanTotalPemasukanPerTahun.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getApiPemasukanTotalPemasukanPerTahunSuspenseQueryKey = (params?: GetApiPemasukanTotalPemasukanPerTahunQueryParams) =>
  [{ url: '/api/Pemasukan/total-pemasukan-per-tahun' }, ...(params ? [params] : [])] as const

export type GetApiPemasukanTotalPemasukanPerTahunSuspenseQueryKey = ReturnType<typeof getApiPemasukanTotalPemasukanPerTahunSuspenseQueryKey>

/**
 * {@link /api/Pemasukan/total-pemasukan-per-tahun}
 */
export async function getApiPemasukanTotalPemasukanPerTahunSuspense(
  params?: GetApiPemasukanTotalPemasukanPerTahunQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiPemasukanTotalPemasukanPerTahunQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/Pemasukan/total-pemasukan-per-tahun`,
    params,
    ...requestConfig,
  })
  return res
}

export function getApiPemasukanTotalPemasukanPerTahunSuspenseQueryOptions(
  params?: GetApiPemasukanTotalPemasukanPerTahunQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = getApiPemasukanTotalPemasukanPerTahunSuspenseQueryKey(params)
  return queryOptions<
    ResponseConfig<GetApiPemasukanTotalPemasukanPerTahunQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiPemasukanTotalPemasukanPerTahunQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiPemasukanTotalPemasukanPerTahunSuspense(params, config)
    },
  })
}

/**
 * {@link /api/Pemasukan/total-pemasukan-per-tahun}
 */
export function useGetApiPemasukanTotalPemasukanPerTahunSuspense<
  TData = ResponseConfig<GetApiPemasukanTotalPemasukanPerTahunQueryResponse>,
  TQueryKey extends QueryKey = GetApiPemasukanTotalPemasukanPerTahunSuspenseQueryKey,
>(
  params?: GetApiPemasukanTotalPemasukanPerTahunQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<ResponseConfig<GetApiPemasukanTotalPemasukanPerTahunQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiPemasukanTotalPemasukanPerTahunSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...(getApiPemasukanTotalPemasukanPerTahunSuspenseQueryOptions(params, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}