/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiPemasukanTotalPemasukanBulanIniQueryResponse } from '../../types/PemasukanController/GetApiPemasukanTotalPemasukanBulanIni.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getApiPemasukanTotalPemasukanBulanIniSuspenseQueryKey = () => [{ url: '/api/Pemasukan/total-pemasukan-bulan-ini' }] as const

export type GetApiPemasukanTotalPemasukanBulanIniSuspenseQueryKey = ReturnType<typeof getApiPemasukanTotalPemasukanBulanIniSuspenseQueryKey>

/**
 * {@link /api/Pemasukan/total-pemasukan-bulan-ini}
 */
export async function getApiPemasukanTotalPemasukanBulanIniSuspense(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiPemasukanTotalPemasukanBulanIniQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/Pemasukan/total-pemasukan-bulan-ini`,
    ...requestConfig,
  })
  return res
}

export function getApiPemasukanTotalPemasukanBulanIniSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiPemasukanTotalPemasukanBulanIniSuspenseQueryKey()
  return queryOptions<
    ResponseConfig<GetApiPemasukanTotalPemasukanBulanIniQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiPemasukanTotalPemasukanBulanIniQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiPemasukanTotalPemasukanBulanIniSuspense(config)
    },
  })
}

/**
 * {@link /api/Pemasukan/total-pemasukan-bulan-ini}
 */
export function useGetApiPemasukanTotalPemasukanBulanIniSuspense<
  TData = ResponseConfig<GetApiPemasukanTotalPemasukanBulanIniQueryResponse>,
  TQueryKey extends QueryKey = GetApiPemasukanTotalPemasukanBulanIniSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<ResponseConfig<GetApiPemasukanTotalPemasukanBulanIniQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiPemasukanTotalPemasukanBulanIniSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...(getApiPemasukanTotalPemasukanBulanIniSuspenseQueryOptions(config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}