/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type {
  GetApiPemasukanTotalPemasukanBulanQueryResponse,
  GetApiPemasukanTotalPemasukanBulanQueryParams,
} from '../../types/PemasukanController/GetApiPemasukanTotalPemasukanBulan.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getApiPemasukanTotalPemasukanBulanQueryKey = (params?: GetApiPemasukanTotalPemasukanBulanQueryParams) =>
  [{ url: '/api/Pemasukan/total-pemasukan-bulan' }, ...(params ? [params] : [])] as const

export type GetApiPemasukanTotalPemasukanBulanQueryKey = ReturnType<typeof getApiPemasukanTotalPemasukanBulanQueryKey>

/**
 * {@link /api/Pemasukan/total-pemasukan-bulan}
 */
export async function getApiPemasukanTotalPemasukanBulan(
  params?: GetApiPemasukanTotalPemasukanBulanQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiPemasukanTotalPemasukanBulanQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/Pemasukan/total-pemasukan-bulan`,
    params,
    ...requestConfig,
  })
  return res
}

export function getApiPemasukanTotalPemasukanBulanQueryOptions(
  params?: GetApiPemasukanTotalPemasukanBulanQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = getApiPemasukanTotalPemasukanBulanQueryKey(params)
  return queryOptions<
    ResponseConfig<GetApiPemasukanTotalPemasukanBulanQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiPemasukanTotalPemasukanBulanQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiPemasukanTotalPemasukanBulan(params, config)
    },
  })
}

/**
 * {@link /api/Pemasukan/total-pemasukan-bulan}
 */
export function useGetApiPemasukanTotalPemasukanBulan<
  TData = ResponseConfig<GetApiPemasukanTotalPemasukanBulanQueryResponse>,
  TQueryData = ResponseConfig<GetApiPemasukanTotalPemasukanBulanQueryResponse>,
  TQueryKey extends QueryKey = GetApiPemasukanTotalPemasukanBulanQueryKey,
>(
  params?: GetApiPemasukanTotalPemasukanBulanQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<ResponseConfig<GetApiPemasukanTotalPemasukanBulanQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiPemasukanTotalPemasukanBulanQueryKey(params)

  const query = useQuery(
    {
      ...(getApiPemasukanTotalPemasukanBulanQueryOptions(params, config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}