/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiPemasukanTotalPemasukanBulanIniQueryResponse } from '../../types/PemasukanController/GetApiPemasukanTotalPemasukanBulanIni.ts'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getApiPemasukanTotalPemasukanBulanIniInfiniteQueryKey = () => [{ url: '/api/Pemasukan/total-pemasukan-bulan-ini' }] as const

export type GetApiPemasukanTotalPemasukanBulanIniInfiniteQueryKey = ReturnType<typeof getApiPemasukanTotalPemasukanBulanIniInfiniteQueryKey>

/**
 * {@link /api/Pemasukan/total-pemasukan-bulan-ini}
 */
export async function getApiPemasukanTotalPemasukanBulanIniInfinite(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiPemasukanTotalPemasukanBulanIniQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/Pemasukan/total-pemasukan-bulan-ini`,
    ...requestConfig,
  })
  return res
}

export function getApiPemasukanTotalPemasukanBulanIniInfiniteQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiPemasukanTotalPemasukanBulanIniInfiniteQueryKey()
  return infiniteQueryOptions<
    ResponseConfig<GetApiPemasukanTotalPemasukanBulanIniQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiPemasukanTotalPemasukanBulanIniQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiPemasukanTotalPemasukanBulanIniInfinite(config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * {@link /api/Pemasukan/total-pemasukan-bulan-ini}
 */
export function useGetApiPemasukanTotalPemasukanBulanIniInfinite<
  TData = InfiniteData<ResponseConfig<GetApiPemasukanTotalPemasukanBulanIniQueryResponse>>,
  TQueryData = ResponseConfig<GetApiPemasukanTotalPemasukanBulanIniQueryResponse>,
  TQueryKey extends QueryKey = GetApiPemasukanTotalPemasukanBulanIniInfiniteQueryKey,
>(
  options: {
    query?: Partial<
      InfiniteQueryObserverOptions<ResponseConfig<GetApiPemasukanTotalPemasukanBulanIniQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiPemasukanTotalPemasukanBulanIniInfiniteQueryKey()

  const query = useInfiniteQuery(
    {
      ...(getApiPemasukanTotalPemasukanBulanIniInfiniteQueryOptions(config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}