/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiPemasukanSaldoQueryResponse } from '../../types/PemasukanController/GetApiPemasukanSaldo.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getApiPemasukanSaldoQueryKey = () => [{ url: '/api/Pemasukan/saldo' }] as const

export type GetApiPemasukanSaldoQueryKey = ReturnType<typeof getApiPemasukanSaldoQueryKey>

/**
 * {@link /api/Pemasukan/saldo}
 */
export async function getApiPemasukanSaldo(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiPemasukanSaldoQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/Pemasukan/saldo`,
    ...requestConfig,
  })
  return res
}

export function getApiPemasukanSaldoQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiPemasukanSaldoQueryKey()
  return queryOptions<
    ResponseConfig<GetApiPemasukanSaldoQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiPemasukanSaldoQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiPemasukanSaldo(config)
    },
  })
}

/**
 * {@link /api/Pemasukan/saldo}
 */
export function useGetApiPemasukanSaldo<
  TData = ResponseConfig<GetApiPemasukanSaldoQueryResponse>,
  TQueryData = ResponseConfig<GetApiPemasukanSaldoQueryResponse>,
  TQueryKey extends QueryKey = GetApiPemasukanSaldoQueryKey,
>(
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<GetApiPemasukanSaldoQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiPemasukanSaldoQueryKey()

  const query = useQuery(
    {
      ...(getApiPemasukanSaldoQueryOptions(config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}