/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiPemasukanSaldoQueryResponse } from '../../types/PemasukanController/GetApiPemasukanSaldo.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getApiPemasukanSaldoSuspenseQueryKey = () => [{ url: '/api/Pemasukan/saldo' }] as const

export type GetApiPemasukanSaldoSuspenseQueryKey = ReturnType<typeof getApiPemasukanSaldoSuspenseQueryKey>

/**
 * {@link /api/Pemasukan/saldo}
 */
export async function getApiPemasukanSaldoSuspense(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiPemasukanSaldoQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/Pemasukan/saldo`,
    ...requestConfig,
  })
  return res
}

export function getApiPemasukanSaldoSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiPemasukanSaldoSuspenseQueryKey()
  return queryOptions<
    ResponseConfig<GetApiPemasukanSaldoQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiPemasukanSaldoQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiPemasukanSaldoSuspense(config)
    },
  })
}

/**
 * {@link /api/Pemasukan/saldo}
 */
export function useGetApiPemasukanSaldoSuspense<
  TData = ResponseConfig<GetApiPemasukanSaldoQueryResponse>,
  TQueryKey extends QueryKey = GetApiPemasukanSaldoSuspenseQueryKey,
>(
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetApiPemasukanSaldoQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiPemasukanSaldoSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...(getApiPemasukanSaldoSuspenseQueryOptions(config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}