/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiPemasukanQueryResponse } from '../../types/PemasukanController/GetApiPemasukan.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getApiPemasukanQueryKey = () => [{ url: '/api/Pemasukan' }] as const

export type GetApiPemasukanQueryKey = ReturnType<typeof getApiPemasukanQueryKey>

/**
 * {@link /api/Pemasukan}
 */
export async function getApiPemasukan(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiPemasukanQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/api/Pemasukan`, ...requestConfig })
  return res
}

export function getApiPemasukanQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiPemasukanQueryKey()
  return queryOptions<ResponseConfig<GetApiPemasukanQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetApiPemasukanQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiPemasukan(config)
    },
  })
}

/**
 * {@link /api/Pemasukan}
 */
export function useGetApiPemasukan<
  TData = ResponseConfig<GetApiPemasukanQueryResponse>,
  TQueryData = ResponseConfig<GetApiPemasukanQueryResponse>,
  TQueryKey extends QueryKey = GetApiPemasukanQueryKey,
>(
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<GetApiPemasukanQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiPemasukanQueryKey()

  const query = useQuery(
    {
      ...(getApiPemasukanQueryOptions(config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}