/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type {
  GetApiPemasukanTotalPemasukanBulanQueryResponse,
  GetApiPemasukanTotalPemasukanBulanQueryParams,
} from '../../types/PemasukanController/GetApiPemasukanTotalPemasukanBulan.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getApiPemasukanTotalPemasukanBulanSuspenseQueryKey = (params?: GetApiPemasukanTotalPemasukanBulanQueryParams) =>
  [{ url: '/api/Pemasukan/total-pemasukan-bulan' }, ...(params ? [params] : [])] as const

export type GetApiPemasukanTotalPemasukanBulanSuspenseQueryKey = ReturnType<typeof getApiPemasukanTotalPemasukanBulanSuspenseQueryKey>

/**
 * {@link /api/Pemasukan/total-pemasukan-bulan}
 */
export async function getApiPemasukanTotalPemasukanBulanSuspense(
  params?: GetApiPemasukanTotalPemasukanBulanQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiPemasukanTotalPemasukanBulanQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/Pemasukan/total-pemasukan-bulan`,
    params,
    ...requestConfig,
  })
  return res
}

export function getApiPemasukanTotalPemasukanBulanSuspenseQueryOptions(
  params?: GetApiPemasukanTotalPemasukanBulanQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = getApiPemasukanTotalPemasukanBulanSuspenseQueryKey(params)
  return queryOptions<
    ResponseConfig<GetApiPemasukanTotalPemasukanBulanQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiPemasukanTotalPemasukanBulanQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiPemasukanTotalPemasukanBulanSuspense(params, config)
    },
  })
}

/**
 * {@link /api/Pemasukan/total-pemasukan-bulan}
 */
export function useGetApiPemasukanTotalPemasukanBulanSuspense<
  TData = ResponseConfig<GetApiPemasukanTotalPemasukanBulanQueryResponse>,
  TQueryKey extends QueryKey = GetApiPemasukanTotalPemasukanBulanSuspenseQueryKey,
>(
  params?: GetApiPemasukanTotalPemasukanBulanQueryParams,
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetApiPemasukanTotalPemasukanBulanQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiPemasukanTotalPemasukanBulanSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...(getApiPemasukanTotalPemasukanBulanSuspenseQueryOptions(params, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}