/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiUsersQueryResponse } from '../../types/UserController/GetApiUsers.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getApiUsersSuspenseQueryKey = () => [{ url: '/api/users' }] as const

export type GetApiUsersSuspenseQueryKey = ReturnType<typeof getApiUsersSuspenseQueryKey>

/**
 * {@link /api/users}
 */
export async function getApiUsersSuspense(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiUsersQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/api/users`, ...requestConfig })
  return res
}

export function getApiUsersSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiUsersSuspenseQueryKey()
  return queryOptions<ResponseConfig<GetApiUsersQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetApiUsersQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiUsersSuspense(config)
    },
  })
}

/**
 * {@link /api/users}
 */
export function useGetApiUsersSuspense<TData = ResponseConfig<GetApiUsersQueryResponse>, TQueryKey extends QueryKey = GetApiUsersSuspenseQueryKey>(
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetApiUsersQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiUsersSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...(getApiUsersSuspenseQueryOptions(config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}