/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiUsersQueryResponse } from '../../types/UserController/GetApiUsers.ts'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getApiUsersInfiniteQueryKey = () => [{ url: '/api/users' }] as const

export type GetApiUsersInfiniteQueryKey = ReturnType<typeof getApiUsersInfiniteQueryKey>

/**
 * {@link /api/users}
 */
export async function getApiUsersInfinite(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiUsersQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/api/users`, ...requestConfig })
  return res
}

export function getApiUsersInfiniteQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiUsersInfiniteQueryKey()
  return infiniteQueryOptions<ResponseConfig<GetApiUsersQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetApiUsersQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiUsersInfinite(config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * {@link /api/users}
 */
export function useGetApiUsersInfinite<
  TData = InfiniteData<ResponseConfig<GetApiUsersQueryResponse>>,
  TQueryData = ResponseConfig<GetApiUsersQueryResponse>,
  TQueryKey extends QueryKey = GetApiUsersInfiniteQueryKey,
>(
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetApiUsersQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiUsersInfiniteQueryKey()

  const query = useInfiniteQuery(
    {
      ...(getApiUsersInfiniteQueryOptions(config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}