/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiUsersQueryResponse } from '../../types/UserController/GetApiUsers.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getApiUsersQueryKey = () => [{ url: '/api/users' }] as const

export type GetApiUsersQueryKey = ReturnType<typeof getApiUsersQueryKey>

/**
 * {@link /api/users}
 */
export async function getApiUsers(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiUsersQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/api/users`, ...requestConfig })
  return res
}

export function getApiUsersQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiUsersQueryKey()
  return queryOptions<ResponseConfig<GetApiUsersQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetApiUsersQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiUsers(config)
    },
  })
}

/**
 * {@link /api/users}
 */
export function useGetApiUsers<
  TData = ResponseConfig<GetApiUsersQueryResponse>,
  TQueryData = ResponseConfig<GetApiUsersQueryResponse>,
  TQueryKey extends QueryKey = GetApiUsersQueryKey,
>(
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<GetApiUsersQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiUsersQueryKey()

  const query = useQuery(
    {
      ...(getApiUsersQueryOptions(config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}