/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiKategoripengeluaranQueryResponse } from '../../types/KategoriPengeluaranController/GetApiKategoripengeluaran.ts'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getApiKategoripengeluaranInfiniteQueryKey = () => [{ url: '/api/KategoriPengeluaran' }] as const

export type GetApiKategoripengeluaranInfiniteQueryKey = ReturnType<typeof getApiKategoripengeluaranInfiniteQueryKey>

/**
 * {@link /api/KategoriPengeluaran}
 */
export async function getApiKategoripengeluaranInfinite(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiKategoripengeluaranQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/KategoriPengeluaran`,
    ...requestConfig,
  })
  return res
}

export function getApiKategoripengeluaranInfiniteQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiKategoripengeluaranInfiniteQueryKey()
  return infiniteQueryOptions<
    ResponseConfig<GetApiKategoripengeluaranQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiKategoripengeluaranQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiKategoripengeluaranInfinite(config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * {@link /api/KategoriPengeluaran}
 */
export function useGetApiKategoripengeluaranInfinite<
  TData = InfiniteData<ResponseConfig<GetApiKategoripengeluaranQueryResponse>>,
  TQueryData = ResponseConfig<GetApiKategoripengeluaranQueryResponse>,
  TQueryKey extends QueryKey = GetApiKategoripengeluaranInfiniteQueryKey,
>(
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetApiKategoripengeluaranQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiKategoripengeluaranInfiniteQueryKey()

  const query = useInfiniteQuery(
    {
      ...(getApiKategoripengeluaranInfiniteQueryOptions(config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}