/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiKategoripengeluaranQueryResponse } from '../../types/KategoriPengeluaranController/GetApiKategoripengeluaran.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getApiKategoripengeluaranSuspenseQueryKey = () => [{ url: '/api/KategoriPengeluaran' }] as const

export type GetApiKategoripengeluaranSuspenseQueryKey = ReturnType<typeof getApiKategoripengeluaranSuspenseQueryKey>

/**
 * {@link /api/KategoriPengeluaran}
 */
export async function getApiKategoripengeluaranSuspense(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiKategoripengeluaranQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/KategoriPengeluaran`,
    ...requestConfig,
  })
  return res
}

export function getApiKategoripengeluaranSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiKategoripengeluaranSuspenseQueryKey()
  return queryOptions<
    ResponseConfig<GetApiKategoripengeluaranQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiKategoripengeluaranQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiKategoripengeluaranSuspense(config)
    },
  })
}

/**
 * {@link /api/KategoriPengeluaran}
 */
export function useGetApiKategoripengeluaranSuspense<
  TData = ResponseConfig<GetApiKategoripengeluaranQueryResponse>,
  TQueryKey extends QueryKey = GetApiKategoripengeluaranSuspenseQueryKey,
>(
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetApiKategoripengeluaranQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiKategoripengeluaranSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...(getApiKategoripengeluaranSuspenseQueryOptions(config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}