/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '@/config/axiosClient.ts'
import type {
  PostApiKategoripengeluaranMutationRequest,
  PostApiKategoripengeluaranMutationResponse,
} from '../../types/KategoriPengeluaranController/PostApiKategoripengeluaran.ts'
import { useMutation } from '@tanstack/react-query'

export const postApiKategoripengeluaranMutationKey = () => [{ url: '/api/KategoriPengeluaran' }] as const

export type PostApiKategoripengeluaranMutationKey = ReturnType<typeof postApiKategoripengeluaranMutationKey>

/**
 * {@link /api/KategoriPengeluaran}
 */
export async function postApiKategoripengeluaran(
  data?: PostApiKategoripengeluaranMutationRequest,
  config: Partial<RequestConfig<PostApiKategoripengeluaranMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<PostApiKategoripengeluaranMutationResponse, ResponseErrorConfig<Error>, PostApiKategoripengeluaranMutationRequest>({
    method: 'POST',
    url: `/api/KategoriPengeluaran`,
    data,
    ...requestConfig,
    headers: { 'Content-Type': 'application/*+json', ...requestConfig.headers },
  })
  return res
}

/**
 * {@link /api/KategoriPengeluaran}
 */
export function usePostApiKategoripengeluaran<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ResponseConfig<PostApiKategoripengeluaranMutationResponse>,
      ResponseErrorConfig<Error>,
      { data?: PostApiKategoripengeluaranMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PostApiKategoripengeluaranMutationRequest>> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? postApiKategoripengeluaranMutationKey()

  return useMutation<
    ResponseConfig<PostApiKategoripengeluaranMutationResponse>,
    ResponseErrorConfig<Error>,
    { data?: PostApiKategoripengeluaranMutationRequest },
    TContext
  >(
    {
      mutationFn: async ({ data }) => {
        return postApiKategoripengeluaran(data, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}