/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetApiPemasukanTotalPemasukanBulanQueryParams = {
  /**
   * @type integer | undefined, int32
   */
  bulan?: number
  /**
   * @type integer | undefined, int32
   */
  tahun?: number
}

/**
 * @description OK
 */
export type GetApiPemasukanTotalPemasukanBulan200 = any

export type GetApiPemasukanTotalPemasukanBulanQueryResponse = GetApiPemasukanTotalPemasukanBulan200

export type GetApiPemasukanTotalPemasukanBulanQuery = {
  Response: GetApiPemasukanTotalPemasukanBulan200
  QueryParams: GetApiPemasukanTotalPemasukanBulanQueryParams
  Errors: any
}