/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetApiPemasukanTotalPemasukanPerTahunQueryParams = {
  /**
   * @type integer | undefined, int32
   */
  tahun?: number
}

/**
 * @description OK
 */
export type GetApiPemasukanTotalPemasukanPerTahun200 = any

export type GetApiPemasukanTotalPemasukanPerTahunQueryResponse = GetApiPemasukanTotalPemasukanPerTahun200

export type GetApiPemasukanTotalPemasukanPerTahunQuery = {
  Response: GetApiPemasukanTotalPemasukanPerTahun200
  QueryParams: GetApiPemasukanTotalPemasukanPerTahunQueryParams
  Errors: any
}