/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description OK
 */
export type GetApiPemasukan200 = any

export type GetApiPemasukanQueryResponse = GetApiPemasukan200

export type GetApiPemasukanQuery = {
  Response: GetApiPemasukan200
  Errors: any
}