/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description OK
 */
export type GetApiPemasukanSaldo200 = any

export type GetApiPemasukanSaldoQueryResponse = GetApiPemasukanSaldo200

export type GetApiPemasukanSaldoQuery = {
  Response: GetApiPemasukanSaldo200
  Errors: any
}