/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description OK
 */
export type GetApiPemasukanTotalPemasukanBulanIni200 = any

export type GetApiPemasukanTotalPemasukanBulanIniQueryResponse = GetApiPemasukanTotalPemasukanBulanIni200

export type GetApiPemasukanTotalPemasukanBulanIniQuery = {
  Response: GetApiPemasukanTotalPemasukanBulanIni200
  Errors: any
}