/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreatePemasukanDto } from '../CreatePemasukanDto.ts'

/**
 * @description OK
 */
export type PostApiPemasukan200 = any

export type PostApiPemasukanMutationRequest = CreatePemasukanDto

export type PostApiPemasukanMutationResponse = PostApiPemasukan200

export type PostApiPemasukanMutation = {
  Response: PostApiPemasukan200
  Request: PostApiPemasukanMutationRequest
  Errors: any
}