/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteApiKategoripengeluaranIdPathParams = {
  /**
   * @type integer, int32
   */
  id: number
}

/**
 * @description OK
 */
export type DeleteApiKategoripengeluaranId200 = any

export type DeleteApiKategoripengeluaranIdMutationResponse = DeleteApiKategoripengeluaranId200

export type DeleteApiKategoripengeluaranIdMutation = {
  Response: DeleteApiKategoripengeluaranId200
  PathParams: DeleteApiKategoripengeluaranIdPathParams
  Errors: any
}