/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { KategoriPengeluaranDto } from '../KategoriPengeluaranDto.ts'

/**
 * @description OK
 */
export type GetApiKategoripengeluaran200 = KategoriPengeluaranDto[]

export type GetApiKategoripengeluaranQueryResponse = GetApiKategoripengeluaran200

export type GetApiKategoripengeluaranQuery = {
  Response: GetApiKategoripengeluaran200
  Errors: any
}