/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { KategoriPengeluaranCreateDto } from '../KategoriPengeluaranCreateDto.ts'

/**
 * @description OK
 */
export type PostApiKategoripengeluaran200 = any

export type PostApiKategoripengeluaranMutationRequest = KategoriPengeluaranCreateDto

export type PostApiKategoripengeluaranMutationResponse = PostApiKategoripengeluaran200

export type PostApiKategoripengeluaranMutation = {
  Response: PostApiKategoripengeluaran200
  Request: PostApiKategoripengeluaranMutationRequest
  Errors: any
}