/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description OK
 */
export type GetApiPengeluaranTotalPengeluaranBulanIni200 = any

export type GetApiPengeluaranTotalPengeluaranBulanIniQueryResponse = GetApiPengeluaranTotalPengeluaranBulanIni200

export type GetApiPengeluaranTotalPengeluaranBulanIniQuery = {
  Response: GetApiPengeluaranTotalPengeluaranBulanIni200
  Errors: any
}