/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PengeluaranPerBulanDto } from '../PengeluaranPerBulanDto.ts'

export type GetApiPengeluaranChartPerBulanQueryParams = {
  /**
   * @type integer | undefined, int32
   */
  tahun?: number
}

/**
 * @description OK
 */
export type GetApiPengeluaranChartPerBulan200 = PengeluaranPerBulanDto[]

export type GetApiPengeluaranChartPerBulanQueryResponse = GetApiPengeluaranChartPerBulan200

export type GetApiPengeluaranChartPerBulanQuery = {
  Response: GetApiPengeluaranChartPerBulan200
  QueryParams: GetApiPengeluaranChartPerBulanQueryParams
  Errors: any
}