/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetApiPengeluaranTotalPengeluaranBulanQueryParams = {
  /**
   * @type integer | undefined, int32
   */
  bulan?: number
  /**
   * @type integer | undefined, int32
   */
  tahun?: number
}

/**
 * @description OK
 */
export type GetApiPengeluaranTotalPengeluaranBulan200 = any

export type GetApiPengeluaranTotalPengeluaranBulanQueryResponse = GetApiPengeluaranTotalPengeluaranBulan200

export type GetApiPengeluaranTotalPengeluaranBulanQuery = {
  Response: GetApiPengeluaranTotalPengeluaranBulan200
  QueryParams: GetApiPengeluaranTotalPengeluaranBulanQueryParams
  Errors: any
}