/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PengeluaranPerTahunDto } from '../PengeluaranPerTahunDto.ts'

/**
 * @description OK
 */
export type GetApiPengeluaranChartPerTahun200 = PengeluaranPerTahunDto[]

export type GetApiPengeluaranChartPerTahunQueryResponse = GetApiPengeluaranChartPerTahun200

export type GetApiPengeluaranChartPerTahunQuery = {
  Response: GetApiPengeluaranChartPerTahun200
  Errors: any
}