/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PengeluaranGetDto } from '../PengeluaranGetDto.ts'

/**
 * @description OK
 */
export type GetApiPengeluaran200 = PengeluaranGetDto[]

export type GetApiPengeluaranQueryResponse = GetApiPengeluaran200

export type GetApiPengeluaranQuery = {
  Response: GetApiPengeluaran200
  Errors: any
}