/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetApiPengeluaranTotalPengeluaranPerTahunQueryParams = {
  /**
   * @type integer | undefined, int32
   */
  tahun?: number
}

/**
 * @description OK
 */
export type GetApiPengeluaranTotalPengeluaranPerTahun200 = any

export type GetApiPengeluaranTotalPengeluaranPerTahunQueryResponse = GetApiPengeluaranTotalPengeluaranPerTahun200

export type GetApiPengeluaranTotalPengeluaranPerTahunQuery = {
  Response: GetApiPengeluaranTotalPengeluaranPerTahun200
  QueryParams: GetApiPengeluaranTotalPengeluaranPerTahunQueryParams
  Errors: any
}