/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PengeluaranCreateDto } from '../PengeluaranCreateDto.ts'

/**
 * @description OK
 */
export type PostApiPengeluaran200 = any

export type PostApiPengeluaranMutationRequest = PengeluaranCreateDto

export type PostApiPengeluaranMutationResponse = PostApiPengeluaran200

export type PostApiPengeluaranMutation = {
  Response: PostApiPengeluaran200
  Request: PostApiPengeluaranMutationRequest
  Errors: any
}