/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteApiRencanabandingIdPathParams = {
  /**
   * @type integer, int32
   */
  id: number
}

/**
 * @description OK
 */
export type DeleteApiRencanabandingId200 = any

export type DeleteApiRencanabandingIdMutationResponse = DeleteApiRencanabandingId200

export type DeleteApiRencanabandingIdMutation = {
  Response: DeleteApiRencanabandingId200
  PathParams: DeleteApiRencanabandingIdPathParams
  Errors: any
}