/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description OK
 */
export type GetApiRencanabanding200 = any

export type GetApiRencanabandingQueryResponse = GetApiRencanabanding200

export type GetApiRencanabandingQuery = {
  Response: GetApiRencanabanding200
  Errors: any
}