/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RencanaBandingCreateDto } from '../RencanaBandingCreateDto.ts'

/**
 * @description OK
 */
export type PostApiRencanabanding200 = any

export type PostApiRencanabandingMutationRequest = RencanaBandingCreateDto

export type PostApiRencanabandingMutationResponse = PostApiRencanabanding200

export type PostApiRencanabandingMutation = {
  Response: PostApiRencanabanding200
  Request: PostApiRencanabandingMutationRequest
  Errors: any
}