/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiPengeluaranChartPerTahunQueryResponse } from '../../types/PengeluaranController/GetApiPengeluaranChartPerTahun.ts'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getApiPengeluaranChartPerTahunInfiniteQueryKey = () => [{ url: '/api/Pengeluaran/chart-per-tahun' }] as const

export type GetApiPengeluaranChartPerTahunInfiniteQueryKey = ReturnType<typeof getApiPengeluaranChartPerTahunInfiniteQueryKey>

/**
 * {@link /api/Pengeluaran/chart-per-tahun}
 */
export async function getApiPengeluaranChartPerTahunInfinite(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiPengeluaranChartPerTahunQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/Pengeluaran/chart-per-tahun`,
    ...requestConfig,
  })
  return res
}

export function getApiPengeluaranChartPerTahunInfiniteQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiPengeluaranChartPerTahunInfiniteQueryKey()
  return infiniteQueryOptions<
    ResponseConfig<GetApiPengeluaranChartPerTahunQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiPengeluaranChartPerTahunQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiPengeluaranChartPerTahunInfinite(config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * {@link /api/Pengeluaran/chart-per-tahun}
 */
export function useGetApiPengeluaranChartPerTahunInfinite<
  TData = InfiniteData<ResponseConfig<GetApiPengeluaranChartPerTahunQueryResponse>>,
  TQueryData = ResponseConfig<GetApiPengeluaranChartPerTahunQueryResponse>,
  TQueryKey extends QueryKey = GetApiPengeluaranChartPerTahunInfiniteQueryKey,
>(
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetApiPengeluaranChartPerTahunQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiPengeluaranChartPerTahunInfiniteQueryKey()

  const query = useInfiniteQuery(
    {
      ...(getApiPengeluaranChartPerTahunInfiniteQueryOptions(config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}