/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type {
  GetApiPengeluaranTotalPengeluaranBulanQueryResponse,
  GetApiPengeluaranTotalPengeluaranBulanQueryParams,
} from '../../types/PengeluaranController/GetApiPengeluaranTotalPengeluaranBulan.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getApiPengeluaranTotalPengeluaranBulanQueryKey = (params?: GetApiPengeluaranTotalPengeluaranBulanQueryParams) =>
  [{ url: '/api/Pengeluaran/total-pengeluaran-bulan' }, ...(params ? [params] : [])] as const

export type GetApiPengeluaranTotalPengeluaranBulanQueryKey = ReturnType<typeof getApiPengeluaranTotalPengeluaranBulanQueryKey>

/**
 * {@link /api/Pengeluaran/total-pengeluaran-bulan}
 */
export async function getApiPengeluaranTotalPengeluaranBulan(
  params?: GetApiPengeluaranTotalPengeluaranBulanQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiPengeluaranTotalPengeluaranBulanQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/Pengeluaran/total-pengeluaran-bulan`,
    params,
    ...requestConfig,
  })
  return res
}

export function getApiPengeluaranTotalPengeluaranBulanQueryOptions(
  params?: GetApiPengeluaranTotalPengeluaranBulanQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = getApiPengeluaranTotalPengeluaranBulanQueryKey(params)
  return queryOptions<
    ResponseConfig<GetApiPengeluaranTotalPengeluaranBulanQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiPengeluaranTotalPengeluaranBulanQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiPengeluaranTotalPengeluaranBulan(params, config)
    },
  })
}

/**
 * {@link /api/Pengeluaran/total-pengeluaran-bulan}
 */
export function useGetApiPengeluaranTotalPengeluaranBulan<
  TData = ResponseConfig<GetApiPengeluaranTotalPengeluaranBulanQueryResponse>,
  TQueryData = ResponseConfig<GetApiPengeluaranTotalPengeluaranBulanQueryResponse>,
  TQueryKey extends QueryKey = GetApiPengeluaranTotalPengeluaranBulanQueryKey,
>(
  params?: GetApiPengeluaranTotalPengeluaranBulanQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<ResponseConfig<GetApiPengeluaranTotalPengeluaranBulanQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiPengeluaranTotalPengeluaranBulanQueryKey(params)

  const query = useQuery(
    {
      ...(getApiPengeluaranTotalPengeluaranBulanQueryOptions(params, config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}