/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type {
  GetApiPengeluaranTotalPengeluaranPerTahunQueryResponse,
  GetApiPengeluaranTotalPengeluaranPerTahunQueryParams,
} from '../../types/PengeluaranController/GetApiPengeluaranTotalPengeluaranPerTahun.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getApiPengeluaranTotalPengeluaranPerTahunSuspenseQueryKey = (params?: GetApiPengeluaranTotalPengeluaranPerTahunQueryParams) =>
  [{ url: '/api/Pengeluaran/total-pengeluaran-per-tahun' }, ...(params ? [params] : [])] as const

export type GetApiPengeluaranTotalPengeluaranPerTahunSuspenseQueryKey = ReturnType<typeof getApiPengeluaranTotalPengeluaranPerTahunSuspenseQueryKey>

/**
 * {@link /api/Pengeluaran/total-pengeluaran-per-tahun}
 */
export async function getApiPengeluaranTotalPengeluaranPerTahunSuspense(
  params?: GetApiPengeluaranTotalPengeluaranPerTahunQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiPengeluaranTotalPengeluaranPerTahunQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/Pengeluaran/total-pengeluaran-per-tahun`,
    params,
    ...requestConfig,
  })
  return res
}

export function getApiPengeluaranTotalPengeluaranPerTahunSuspenseQueryOptions(
  params?: GetApiPengeluaranTotalPengeluaranPerTahunQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = getApiPengeluaranTotalPengeluaranPerTahunSuspenseQueryKey(params)
  return queryOptions<
    ResponseConfig<GetApiPengeluaranTotalPengeluaranPerTahunQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiPengeluaranTotalPengeluaranPerTahunQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiPengeluaranTotalPengeluaranPerTahunSuspense(params, config)
    },
  })
}

/**
 * {@link /api/Pengeluaran/total-pengeluaran-per-tahun}
 */
export function useGetApiPengeluaranTotalPengeluaranPerTahunSuspense<
  TData = ResponseConfig<GetApiPengeluaranTotalPengeluaranPerTahunQueryResponse>,
  TQueryKey extends QueryKey = GetApiPengeluaranTotalPengeluaranPerTahunSuspenseQueryKey,
>(
  params?: GetApiPengeluaranTotalPengeluaranPerTahunQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<ResponseConfig<GetApiPengeluaranTotalPengeluaranPerTahunQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiPengeluaranTotalPengeluaranPerTahunSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...(getApiPengeluaranTotalPengeluaranPerTahunSuspenseQueryOptions(params, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}