/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type {
  GetApiPengeluaranTotalPengeluaranPerTahunQueryResponse,
  GetApiPengeluaranTotalPengeluaranPerTahunQueryParams,
} from '../../types/PengeluaranController/GetApiPengeluaranTotalPengeluaranPerTahun.ts'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getApiPengeluaranTotalPengeluaranPerTahunInfiniteQueryKey = (params?: GetApiPengeluaranTotalPengeluaranPerTahunQueryParams) =>
  [{ url: '/api/Pengeluaran/total-pengeluaran-per-tahun' }, ...(params ? [params] : [])] as const

export type GetApiPengeluaranTotalPengeluaranPerTahunInfiniteQueryKey = ReturnType<typeof getApiPengeluaranTotalPengeluaranPerTahunInfiniteQueryKey>

/**
 * {@link /api/Pengeluaran/total-pengeluaran-per-tahun}
 */
export async function getApiPengeluaranTotalPengeluaranPerTahunInfinite(
  params?: GetApiPengeluaranTotalPengeluaranPerTahunQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiPengeluaranTotalPengeluaranPerTahunQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/Pengeluaran/total-pengeluaran-per-tahun`,
    params,
    ...requestConfig,
  })
  return res
}

export function getApiPengeluaranTotalPengeluaranPerTahunInfiniteQueryOptions(
  params?: GetApiPengeluaranTotalPengeluaranPerTahunQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = getApiPengeluaranTotalPengeluaranPerTahunInfiniteQueryKey(params)
  return infiniteQueryOptions<
    ResponseConfig<GetApiPengeluaranTotalPengeluaranPerTahunQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiPengeluaranTotalPengeluaranPerTahunQueryResponse>,
    typeof queryKey,
    number
  >({
    queryKey,
    queryFn: async ({ signal, pageParam }) => {
      config.signal = signal

      if (params) {
        params['next_page'] = pageParam as unknown as GetApiPengeluaranTotalPengeluaranPerTahunQueryParams['next_page']
      }
      return getApiPengeluaranTotalPengeluaranPerTahunInfinite(params, config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * {@link /api/Pengeluaran/total-pengeluaran-per-tahun}
 */
export function useGetApiPengeluaranTotalPengeluaranPerTahunInfinite<
  TData = InfiniteData<ResponseConfig<GetApiPengeluaranTotalPengeluaranPerTahunQueryResponse>>,
  TQueryData = ResponseConfig<GetApiPengeluaranTotalPengeluaranPerTahunQueryResponse>,
  TQueryKey extends QueryKey = GetApiPengeluaranTotalPengeluaranPerTahunInfiniteQueryKey,
>(
  params?: GetApiPengeluaranTotalPengeluaranPerTahunQueryParams,
  options: {
    query?: Partial<
      InfiniteQueryObserverOptions<ResponseConfig<GetApiPengeluaranTotalPengeluaranPerTahunQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiPengeluaranTotalPengeluaranPerTahunInfiniteQueryKey(params)

  const query = useInfiniteQuery(
    {
      ...(getApiPengeluaranTotalPengeluaranPerTahunInfiniteQueryOptions(params, config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}