/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiPengeluaranChartPerTahunQueryResponse } from '../../types/PengeluaranController/GetApiPengeluaranChartPerTahun.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getApiPengeluaranChartPerTahunQueryKey = () => [{ url: '/api/Pengeluaran/chart-per-tahun' }] as const

export type GetApiPengeluaranChartPerTahunQueryKey = ReturnType<typeof getApiPengeluaranChartPerTahunQueryKey>

/**
 * {@link /api/Pengeluaran/chart-per-tahun}
 */
export async function getApiPengeluaranChartPerTahun(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiPengeluaranChartPerTahunQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/Pengeluaran/chart-per-tahun`,
    ...requestConfig,
  })
  return res
}

export function getApiPengeluaranChartPerTahunQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiPengeluaranChartPerTahunQueryKey()
  return queryOptions<
    ResponseConfig<GetApiPengeluaranChartPerTahunQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiPengeluaranChartPerTahunQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiPengeluaranChartPerTahun(config)
    },
  })
}

/**
 * {@link /api/Pengeluaran/chart-per-tahun}
 */
export function useGetApiPengeluaranChartPerTahun<
  TData = ResponseConfig<GetApiPengeluaranChartPerTahunQueryResponse>,
  TQueryData = ResponseConfig<GetApiPengeluaranChartPerTahunQueryResponse>,
  TQueryKey extends QueryKey = GetApiPengeluaranChartPerTahunQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<ResponseConfig<GetApiPengeluaranChartPerTahunQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiPengeluaranChartPerTahunQueryKey()

  const query = useQuery(
    {
      ...(getApiPengeluaranChartPerTahunQueryOptions(config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}