/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiPengeluaranTotalPengeluaranBulanIniQueryResponse } from '../../types/PengeluaranController/GetApiPengeluaranTotalPengeluaranBulanIni.ts'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getApiPengeluaranTotalPengeluaranBulanIniInfiniteQueryKey = () => [{ url: '/api/Pengeluaran/total-pengeluaran-bulan-ini' }] as const

export type GetApiPengeluaranTotalPengeluaranBulanIniInfiniteQueryKey = ReturnType<typeof getApiPengeluaranTotalPengeluaranBulanIniInfiniteQueryKey>

/**
 * {@link /api/Pengeluaran/total-pengeluaran-bulan-ini}
 */
export async function getApiPengeluaranTotalPengeluaranBulanIniInfinite(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiPengeluaranTotalPengeluaranBulanIniQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/Pengeluaran/total-pengeluaran-bulan-ini`,
    ...requestConfig,
  })
  return res
}

export function getApiPengeluaranTotalPengeluaranBulanIniInfiniteQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiPengeluaranTotalPengeluaranBulanIniInfiniteQueryKey()
  return infiniteQueryOptions<
    ResponseConfig<GetApiPengeluaranTotalPengeluaranBulanIniQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiPengeluaranTotalPengeluaranBulanIniQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiPengeluaranTotalPengeluaranBulanIniInfinite(config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * {@link /api/Pengeluaran/total-pengeluaran-bulan-ini}
 */
export function useGetApiPengeluaranTotalPengeluaranBulanIniInfinite<
  TData = InfiniteData<ResponseConfig<GetApiPengeluaranTotalPengeluaranBulanIniQueryResponse>>,
  TQueryData = ResponseConfig<GetApiPengeluaranTotalPengeluaranBulanIniQueryResponse>,
  TQueryKey extends QueryKey = GetApiPengeluaranTotalPengeluaranBulanIniInfiniteQueryKey,
>(
  options: {
    query?: Partial<
      InfiniteQueryObserverOptions<ResponseConfig<GetApiPengeluaranTotalPengeluaranBulanIniQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiPengeluaranTotalPengeluaranBulanIniInfiniteQueryKey()

  const query = useInfiniteQuery(
    {
      ...(getApiPengeluaranTotalPengeluaranBulanIniInfiniteQueryOptions(config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}