/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiPengeluaranTotalPengeluaranBulanIniQueryResponse } from '../../types/PengeluaranController/GetApiPengeluaranTotalPengeluaranBulanIni.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getApiPengeluaranTotalPengeluaranBulanIniSuspenseQueryKey = () => [{ url: '/api/Pengeluaran/total-pengeluaran-bulan-ini' }] as const

export type GetApiPengeluaranTotalPengeluaranBulanIniSuspenseQueryKey = ReturnType<typeof getApiPengeluaranTotalPengeluaranBulanIniSuspenseQueryKey>

/**
 * {@link /api/Pengeluaran/total-pengeluaran-bulan-ini}
 */
export async function getApiPengeluaranTotalPengeluaranBulanIniSuspense(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiPengeluaranTotalPengeluaranBulanIniQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/Pengeluaran/total-pengeluaran-bulan-ini`,
    ...requestConfig,
  })
  return res
}

export function getApiPengeluaranTotalPengeluaranBulanIniSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiPengeluaranTotalPengeluaranBulanIniSuspenseQueryKey()
  return queryOptions<
    ResponseConfig<GetApiPengeluaranTotalPengeluaranBulanIniQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiPengeluaranTotalPengeluaranBulanIniQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiPengeluaranTotalPengeluaranBulanIniSuspense(config)
    },
  })
}

/**
 * {@link /api/Pengeluaran/total-pengeluaran-bulan-ini}
 */
export function useGetApiPengeluaranTotalPengeluaranBulanIniSuspense<
  TData = ResponseConfig<GetApiPengeluaranTotalPengeluaranBulanIniQueryResponse>,
  TQueryKey extends QueryKey = GetApiPengeluaranTotalPengeluaranBulanIniSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<ResponseConfig<GetApiPengeluaranTotalPengeluaranBulanIniQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiPengeluaranTotalPengeluaranBulanIniSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...(getApiPengeluaranTotalPengeluaranBulanIniSuspenseQueryOptions(config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}