/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiPengeluaranQueryResponse } from '../../types/PengeluaranController/GetApiPengeluaran.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getApiPengeluaranSuspenseQueryKey = () => [{ url: '/api/Pengeluaran' }] as const

export type GetApiPengeluaranSuspenseQueryKey = ReturnType<typeof getApiPengeluaranSuspenseQueryKey>

/**
 * {@link /api/Pengeluaran}
 */
export async function getApiPengeluaranSuspense(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiPengeluaranQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/api/Pengeluaran`, ...requestConfig })
  return res
}

export function getApiPengeluaranSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiPengeluaranSuspenseQueryKey()
  return queryOptions<
    ResponseConfig<GetApiPengeluaranQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiPengeluaranQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiPengeluaranSuspense(config)
    },
  })
}

/**
 * {@link /api/Pengeluaran}
 */
export function useGetApiPengeluaranSuspense<
  TData = ResponseConfig<GetApiPengeluaranQueryResponse>,
  TQueryKey extends QueryKey = GetApiPengeluaranSuspenseQueryKey,
>(
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetApiPengeluaranQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiPengeluaranSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...(getApiPengeluaranSuspenseQueryOptions(config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}