/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiPengeluaranQueryResponse } from '../../types/PengeluaranController/GetApiPengeluaran.ts'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getApiPengeluaranInfiniteQueryKey = () => [{ url: '/api/Pengeluaran' }] as const

export type GetApiPengeluaranInfiniteQueryKey = ReturnType<typeof getApiPengeluaranInfiniteQueryKey>

/**
 * {@link /api/Pengeluaran}
 */
export async function getApiPengeluaranInfinite(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiPengeluaranQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/api/Pengeluaran`, ...requestConfig })
  return res
}

export function getApiPengeluaranInfiniteQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiPengeluaranInfiniteQueryKey()
  return infiniteQueryOptions<
    ResponseConfig<GetApiPengeluaranQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiPengeluaranQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiPengeluaranInfinite(config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * {@link /api/Pengeluaran}
 */
export function useGetApiPengeluaranInfinite<
  TData = InfiniteData<ResponseConfig<GetApiPengeluaranQueryResponse>>,
  TQueryData = ResponseConfig<GetApiPengeluaranQueryResponse>,
  TQueryKey extends QueryKey = GetApiPengeluaranInfiniteQueryKey,
>(
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetApiPengeluaranQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiPengeluaranInfiniteQueryKey()

  const query = useInfiniteQuery(
    {
      ...(getApiPengeluaranInfiniteQueryOptions(config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}