/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type {
  GetApiPengeluaranChartPerBulanQueryResponse,
  GetApiPengeluaranChartPerBulanQueryParams,
} from '../../types/PengeluaranController/GetApiPengeluaranChartPerBulan.ts'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getApiPengeluaranChartPerBulanInfiniteQueryKey = (params?: GetApiPengeluaranChartPerBulanQueryParams) =>
  [{ url: '/api/Pengeluaran/chart-per-bulan' }, ...(params ? [params] : [])] as const

export type GetApiPengeluaranChartPerBulanInfiniteQueryKey = ReturnType<typeof getApiPengeluaranChartPerBulanInfiniteQueryKey>

/**
 * {@link /api/Pengeluaran/chart-per-bulan}
 */
export async function getApiPengeluaranChartPerBulanInfinite(
  params?: GetApiPengeluaranChartPerBulanQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiPengeluaranChartPerBulanQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/Pengeluaran/chart-per-bulan`,
    params,
    ...requestConfig,
  })
  return res
}

export function getApiPengeluaranChartPerBulanInfiniteQueryOptions(
  params?: GetApiPengeluaranChartPerBulanQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = getApiPengeluaranChartPerBulanInfiniteQueryKey(params)
  return infiniteQueryOptions<
    ResponseConfig<GetApiPengeluaranChartPerBulanQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiPengeluaranChartPerBulanQueryResponse>,
    typeof queryKey,
    number
  >({
    queryKey,
    queryFn: async ({ signal, pageParam }) => {
      config.signal = signal

      if (params) {
        params['next_page'] = pageParam as unknown as GetApiPengeluaranChartPerBulanQueryParams['next_page']
      }
      return getApiPengeluaranChartPerBulanInfinite(params, config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * {@link /api/Pengeluaran/chart-per-bulan}
 */
export function useGetApiPengeluaranChartPerBulanInfinite<
  TData = InfiniteData<ResponseConfig<GetApiPengeluaranChartPerBulanQueryResponse>>,
  TQueryData = ResponseConfig<GetApiPengeluaranChartPerBulanQueryResponse>,
  TQueryKey extends QueryKey = GetApiPengeluaranChartPerBulanInfiniteQueryKey,
>(
  params?: GetApiPengeluaranChartPerBulanQueryParams,
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetApiPengeluaranChartPerBulanQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiPengeluaranChartPerBulanInfiniteQueryKey(params)

  const query = useInfiniteQuery(
    {
      ...(getApiPengeluaranChartPerBulanInfiniteQueryOptions(params, config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}