/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type {
  GetApiPengeluaranTotalPengeluaranPerTahunQueryResponse,
  GetApiPengeluaranTotalPengeluaranPerTahunQueryParams,
} from '../../types/PengeluaranController/GetApiPengeluaranTotalPengeluaranPerTahun.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getApiPengeluaranTotalPengeluaranPerTahunQueryKey = (params?: GetApiPengeluaranTotalPengeluaranPerTahunQueryParams) =>
  [{ url: '/api/Pengeluaran/total-pengeluaran-per-tahun' }, ...(params ? [params] : [])] as const

export type GetApiPengeluaranTotalPengeluaranPerTahunQueryKey = ReturnType<typeof getApiPengeluaranTotalPengeluaranPerTahunQueryKey>

/**
 * {@link /api/Pengeluaran/total-pengeluaran-per-tahun}
 */
export async function getApiPengeluaranTotalPengeluaranPerTahun(
  params?: GetApiPengeluaranTotalPengeluaranPerTahunQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiPengeluaranTotalPengeluaranPerTahunQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/Pengeluaran/total-pengeluaran-per-tahun`,
    params,
    ...requestConfig,
  })
  return res
}

export function getApiPengeluaranTotalPengeluaranPerTahunQueryOptions(
  params?: GetApiPengeluaranTotalPengeluaranPerTahunQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = getApiPengeluaranTotalPengeluaranPerTahunQueryKey(params)
  return queryOptions<
    ResponseConfig<GetApiPengeluaranTotalPengeluaranPerTahunQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiPengeluaranTotalPengeluaranPerTahunQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiPengeluaranTotalPengeluaranPerTahun(params, config)
    },
  })
}

/**
 * {@link /api/Pengeluaran/total-pengeluaran-per-tahun}
 */
export function useGetApiPengeluaranTotalPengeluaranPerTahun<
  TData = ResponseConfig<GetApiPengeluaranTotalPengeluaranPerTahunQueryResponse>,
  TQueryData = ResponseConfig<GetApiPengeluaranTotalPengeluaranPerTahunQueryResponse>,
  TQueryKey extends QueryKey = GetApiPengeluaranTotalPengeluaranPerTahunQueryKey,
>(
  params?: GetApiPengeluaranTotalPengeluaranPerTahunQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<ResponseConfig<GetApiPengeluaranTotalPengeluaranPerTahunQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiPengeluaranTotalPengeluaranPerTahunQueryKey(params)

  const query = useQuery(
    {
      ...(getApiPengeluaranTotalPengeluaranPerTahunQueryOptions(params, config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}