/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type {
  GetApiPengeluaranChartPerBulanQueryResponse,
  GetApiPengeluaranChartPerBulanQueryParams,
} from '../../types/PengeluaranController/GetApiPengeluaranChartPerBulan.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getApiPengeluaranChartPerBulanQueryKey = (params?: GetApiPengeluaranChartPerBulanQueryParams) =>
  [{ url: '/api/Pengeluaran/chart-per-bulan' }, ...(params ? [params] : [])] as const

export type GetApiPengeluaranChartPerBulanQueryKey = ReturnType<typeof getApiPengeluaranChartPerBulanQueryKey>

/**
 * {@link /api/Pengeluaran/chart-per-bulan}
 */
export async function getApiPengeluaranChartPerBulan(
  params?: GetApiPengeluaranChartPerBulanQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiPengeluaranChartPerBulanQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/Pengeluaran/chart-per-bulan`,
    params,
    ...requestConfig,
  })
  return res
}

export function getApiPengeluaranChartPerBulanQueryOptions(
  params?: GetApiPengeluaranChartPerBulanQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = getApiPengeluaranChartPerBulanQueryKey(params)
  return queryOptions<
    ResponseConfig<GetApiPengeluaranChartPerBulanQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiPengeluaranChartPerBulanQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiPengeluaranChartPerBulan(params, config)
    },
  })
}

/**
 * {@link /api/Pengeluaran/chart-per-bulan}
 */
export function useGetApiPengeluaranChartPerBulan<
  TData = ResponseConfig<GetApiPengeluaranChartPerBulanQueryResponse>,
  TQueryData = ResponseConfig<GetApiPengeluaranChartPerBulanQueryResponse>,
  TQueryKey extends QueryKey = GetApiPengeluaranChartPerBulanQueryKey,
>(
  params?: GetApiPengeluaranChartPerBulanQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<ResponseConfig<GetApiPengeluaranChartPerBulanQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiPengeluaranChartPerBulanQueryKey(params)

  const query = useQuery(
    {
      ...(getApiPengeluaranChartPerBulanQueryOptions(params, config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}