/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiPengeluaranChartPerTahunQueryResponse } from '../../types/PengeluaranController/GetApiPengeluaranChartPerTahun.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getApiPengeluaranChartPerTahunSuspenseQueryKey = () => [{ url: '/api/Pengeluaran/chart-per-tahun' }] as const

export type GetApiPengeluaranChartPerTahunSuspenseQueryKey = ReturnType<typeof getApiPengeluaranChartPerTahunSuspenseQueryKey>

/**
 * {@link /api/Pengeluaran/chart-per-tahun}
 */
export async function getApiPengeluaranChartPerTahunSuspense(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiPengeluaranChartPerTahunQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/Pengeluaran/chart-per-tahun`,
    ...requestConfig,
  })
  return res
}

export function getApiPengeluaranChartPerTahunSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiPengeluaranChartPerTahunSuspenseQueryKey()
  return queryOptions<
    ResponseConfig<GetApiPengeluaranChartPerTahunQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiPengeluaranChartPerTahunQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiPengeluaranChartPerTahunSuspense(config)
    },
  })
}

/**
 * {@link /api/Pengeluaran/chart-per-tahun}
 */
export function useGetApiPengeluaranChartPerTahunSuspense<
  TData = ResponseConfig<GetApiPengeluaranChartPerTahunQueryResponse>,
  TQueryKey extends QueryKey = GetApiPengeluaranChartPerTahunSuspenseQueryKey,
>(
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetApiPengeluaranChartPerTahunQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiPengeluaranChartPerTahunSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...(getApiPengeluaranChartPerTahunSuspenseQueryOptions(config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}