/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/config/axiosClient.ts'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@/config/axiosClient.ts'
import type { GetApiPengeluaranQueryResponse } from '../../types/PengeluaranController/GetApiPengeluaran.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getApiPengeluaranQueryKey = () => [{ url: '/api/Pengeluaran' }] as const

export type GetApiPengeluaranQueryKey = ReturnType<typeof getApiPengeluaranQueryKey>

/**
 * {@link /api/Pengeluaran}
 */
export async function getApiPengeluaran(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetApiPengeluaranQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/api/Pengeluaran`, ...requestConfig })
  return res
}

export function getApiPengeluaranQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getApiPengeluaranQueryKey()
  return queryOptions<
    ResponseConfig<GetApiPengeluaranQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetApiPengeluaranQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getApiPengeluaran(config)
    },
  })
}

/**
 * {@link /api/Pengeluaran}
 */
export function useGetApiPengeluaran<
  TData = ResponseConfig<GetApiPengeluaranQueryResponse>,
  TQueryData = ResponseConfig<GetApiPengeluaranQueryResponse>,
  TQueryKey extends QueryKey = GetApiPengeluaranQueryKey,
>(
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<GetApiPengeluaranQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getApiPengeluaranQueryKey()

  const query = useQuery(
    {
      ...(getApiPengeluaranQueryOptions(config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}